- build.xml
- conf/db-ignore-external-exemptions.txt
- conf/nutch-default.xml
- src/java/org/apache/nutch/fetcher/FetcherThread.java
- src/java/org/apache/nutch/net/URLExemptionFilter.java
- src/java/org/apache/nutch/net/URLExemptionFilters.java
- src/java/org/apache/nutch/parse/ParseOutputFormat.java
- src/java/org/apache/nutch/plugin/ExtensionPoint.java
- src/plugin/build.xml
- src/plugin/nutch-extensionpoints/plugin.xml
- src/plugin/urlfilter-ignoreexempt/README.md
- src/plugin/urlfilter-ignoreexempt/build.xml
- src/plugin/urlfilter-ignoreexempt/ivy.xml
- src/plugin/urlfilter-ignoreexempt/plugin.xml
- src/plugin/urlfilter-ignoreexempt/src/java/org/apache/nutch/urlfilter/ignoreexempt/ExemptionUrlFilter.java
- src/plugin/urlfilter-ignoreexempt/src/java/org/apache/nutch/urlfilter/ignoreexempt/package-info.java
This PR is a duplicate of #89 
Recreated due to the issues caused while moving to writable git.
@chrismattmann
> NUTCH-2144 Added an extension point and a plugin to accept external links

- src/plugin/index-basic/src/java/org/apache/nutch/indexer/basic/BasicIndexingFilter.java
The tstamp was everytime equal to "1970-01-01T00:00:00.000Z" cause of this.
> Fix the issue of the bad tstamp

- conf/nutch-default.xml
- src/java/org/apache/nutch/indexer/IndexingFiltersChecker.java
- src/plugin/parse-tika/src/java/org/apache/nutch/parse/tika/BoilerpipeExtractorRepository.java
- src/plugin/parse-tika/src/java/org/apache/nutch/parse/tika/DOMBuilder.java
- src/plugin/parse-tika/src/java/org/apache/nutch/parse/tika/TikaParser.java
I adapted a bit the patch from the [NUTCH-961](https://issues.apache.org/jira/browse/NUTCH-961). This patch add the boilerpipe parser in nutch which improve a lot the quality of parser.
> Add the boilerpipe parsing adapted from NUTCH-961

- src/plugin/build.xml
- src/plugin/indexer-elastic2/build-ivy.xml
- src/plugin/indexer-elastic2/build.xml
- src/plugin/indexer-elastic2/howto_upgrade_es.txt
- src/plugin/indexer-elastic2/ivy.xml
- src/plugin/indexer-elastic2/plugin.xml
- src/plugin/indexer-elastic2/src/java/org/apache/nutch/indexwriter/elastic2/ElasticConstants.java
- src/plugin/indexer-elastic2/src/java/org/apache/nutch/indexwriter/elastic2/ElasticIndexWriter.java
- src/plugin/indexer-elastic2/src/java/org/apache/nutch/indexwriter/elastic2/package-info.java
Add a new plugin for Elasticsearch 2.x based on indexer-elastic
> fix for NUTCH-2238 contributed by ptorrestr

- conf/nutch-default.xml
- src/plugin/lib-selenium/src/java/org/apache/nutch/protocol/selenium/HttpWebClient.java
- src/plugin/protocol-selenium/README.md
Added phantomJS libs to allow use with Selenium local or Grid options & updated docs
> Nutch-2252: Allow phantomjs as a browser for selenium options

- docker/hbase/Dockerfile
after the link to nutch is created
> NUTCH-2259 - moved creation of nutch logs folder 

- docker/hbase/Dockerfile
This PR addresses https://issues.apache.org/jira/browse/NUTCH-2260
> NUTCH-2260 JAVA_HOME and hbase-common dependency absent from hbase Docker image

- conf/nutch-default.xml
- src/plugin/scoring-similarity/src/java/org/apache/nutch/scoring/similarity/cosine/CosineSimilarity.java
- src/plugin/scoring-similarity/src/java/org/apache/nutch/scoring/similarity/cosine/Model.java
- src/plugin/scoring-similarity/src/java/org/apache/nutch/scoring/similarity/util/LuceneTokenizer.java
mingram and maxgram support for Unigram Cosine Similarity Model is provided.
> NUTCH-2263 Support for mingram and maxgram at Unigram Cosine Similarity Model

- src/java/org/apache/nutch/fetcher/FetchItem.java
- src/java/org/apache/nutch/fetcher/Fetcher.java
- src/java/org/apache/nutch/fetcher/FetcherOutputFormat.java
This issue addresses https://issues.apache.org/jira/browse/NUTCH-2262
> NUTCH-2262 Utilize parameterized logging notation across Fetcher

- ivy/ivy.xml
- ivy/mvn.template
- src/java/org/apache/nutch/fetcher/Fetcher.java
This issue addresses https://issues.apache.org/jira/browse/NUTCH-2329
> NUTH-2329 Update Slf4j logging for Java 8 and upgrade miredot plugin version

- src/java/org/apache/nutch/metadata/Metadata.java
This issue addresses https://issues.apache.org/jira/browse/NUTCH-2346
> NUTCH-2346v2 Check Types at Object Equality v2

- src/java/org/apache/nutch/crawl/CrawlDb.java
- src/java/org/apache/nutch/crawl/CrawlDbMerger.java
- src/java/org/apache/nutch/crawl/CrawlDbReader.java
- src/java/org/apache/nutch/crawl/DeduplicationJob.java
- src/java/org/apache/nutch/crawl/Generator.java
- src/java/org/apache/nutch/crawl/Injector.java
- src/java/org/apache/nutch/crawl/LinkDb.java
- src/java/org/apache/nutch/crawl/LinkDbMerger.java
- src/java/org/apache/nutch/crawl/LinkDbReader.java
- src/java/org/apache/nutch/hostdb/UpdateHostDb.java
- src/java/org/apache/nutch/indexer/IndexerMapReduce.java
- src/java/org/apache/nutch/indexer/IndexingJob.java
- src/java/org/apache/nutch/parse/ParseSegment.java
- src/java/org/apache/nutch/scoring/webgraph/LinkDumper.java
- src/java/org/apache/nutch/scoring/webgraph/LinkRank.java
- src/java/org/apache/nutch/scoring/webgraph/NodeReader.java
- src/java/org/apache/nutch/scoring/webgraph/ScoreUpdater.java
- src/java/org/apache/nutch/scoring/webgraph/WebGraph.java
- src/java/org/apache/nutch/segment/SegmentMerger.java
- src/java/org/apache/nutch/segment/SegmentReader.java
- src/java/org/apache/nutch/tools/CommonCrawlDataDumper.java
- src/java/org/apache/nutch/tools/FileDumper.java
- src/java/org/apache/nutch/util/LockUtil.java
Instead of
FileSystem fs = FileSystem.get(getConf());
use
FileSystem fs = path.getFileSystem(getConf());
to make sure that FileSystem and Path match.
> NUTCH-2281 Support non-default FileSystem

- conf/nutch-default.xml
- src/plugin/publish-rabbitmq/plugin.xml
- src/plugin/publish-rabbitmq/src/java/org/apache/nutch/publisher/rabbitmq/RabbitMQPublisherImpl.java
Added new properties and fixed a ClassNotFoundException.
> fix for NUTCH-2132 contributed by r0ann3l

- docker/cassandra/README.md
> Fix markdown header syntax

- src/plugin/parse-tika/src/java/org/apache/nutch/parse/tika/DOMContentUtils.java
Added condition that will separate paragraph line breaks.
> Read Paragraph Line Breaks

- src/plugin/jsoup-extractor/build.xml
- src/plugin/jsoup-extractor/src/test/org/apache/nutch/parse/jsoup/extractor/TestJsoupHtmlParser.java
Failed Jenkin build #1588 after merging pull request #192 (NUTCH-2389) issue solved. Now build successfully and unit test passed.
> NUTCH-2404 Fix for Failed Jenkin build #1588 after merging pull request #192 (NUTCH-2389).

- src/java/org/apache/nutch/crawl/AbstractFetchSchedule.java
- src/java/org/apache/nutch/crawl/CrawlDatum.java
- src/java/org/apache/nutch/net/URLExemptionFilter.java
- src/java/org/apache/nutch/net/URLNormalizers.java
See https://issues.apache.org/jira/browse/NUTCH-2406 for details.
> NUTCH-2406 Minor improvements

- conf/jsoup-extractor-example.xml
- conf/jsoup-extractor.xml
- src/plugin/jsoup-extractor/src/java/org/apache/nutch/parse/jsoup/extractor/JsoupHtmlParser.java
Several bugs faced during testing with my project have been fixed
1. Missed root tag <extractor> added in jsoup-extractor.xml like jsoup-extractor-example.xml
2. jsoup API text() used instead of ownText() to get full contents under CSS selector
3. <default> => <default-value> typo fixed
> Issues mentioned in NUTCH-2405 fixed

- conf/schema.xml
This issues addresses https://issues.apache.org/jira/browse/NUTCH-2400
I decided to create the PR with minimal changes e.g. create a diff against schema.xml rather than upload the managed-schema.
> NUTCH-2400 Solr 6.6.0 compatibility

- src/java/org/apache/nutch/plugin/PluginClassLoader.java
- src/plugin/indexer-solr/plugin.xml
- src/plugin/parse-tika/ivy.xml
- src/plugin/parse-tika/plugin.xml
- src/plugin/parsefilter-naivebayes/plugin.xml
(contributed by Jurian Broertjes)
> NUTCH-2378 ChildFirst plugin classloader

- src/java/org/apache/nutch/fetcher/FetcherThread.java
This is my fix proposal for NUTCH-2413 issue.
> fix for NUTCH-2413 contributed by maborec

- src/java/org/apache/nutch/crawl/Injector.java
- add counters for items removed from CrawlDb
- add -Ddb.update.purge.404=true to command-line help
> NUTCH-2409 Injector: complete command-line help and counters

- conf/gora-mongodb-mapping.xml
@lewismc : Please welcome my first contribution with this trivial fix.
> fix for NUTCH-2437 contributed by tmzzngl

- src/java/org/apache/nutch/crawl/URLPartitioner.java
- src/java/org/apache/nutch/tools/CommonCrawlDataDumper.java
- src/plugin/index-more/src/java/org/apache/nutch/indexer/more/MoreIndexingFilter.java
- src/plugin/indexer-elastic/src/java/org/apache/nutch/indexwriter/elastic/ElasticIndexWriter.java
- src/plugin/urlnormalizer-host/src/java/org/apache/nutch/net/urlnormalizer/host/HostURLNormalizer.java
- src/plugin/urlnormalizer-protocol/src/java/org/apache/nutch/net/urlnormalizer/protocol/ProtocolURLNormalizer.java
- src/plugin/urlnormalizer-slash/src/java/org/apache/nutch/net/urlnormalizer/slash/SlashURLNormalizer.java
- String.trim() without assignment
- avoid strings to fail as regex.Pattern
- possible NPE in URLPartitioner: reworked code
> NUTCH-2394 Fix of bugs detected by static code analysis

- src/java/org/apache/nutch/crawl/Injector.java
- src/java/org/apache/nutch/hostdb/ReadHostDb.java
- src/java/org/apache/nutch/util/CrawlCompletionStats.java
- src/java/org/apache/nutch/util/ProtocolStatusStatistics.java
- src/java/org/apache/nutch/util/SitemapProcessor.java
- src/java/org/apache/nutch/util/domain/DomainStatistics.java
- Added Job status checks in the classes: Injector, ReadHostDb, CrawlCompletionStats, ProtocolStatusStatistics, SitemapProcessor and DomainStatistics.
> NUTCH-2442 Injector to stop if job fails to avoid loss of CrawlDb

- src/java/org/apache/nutch/crawl/CrawlDbReader.java
Added the parameter -sample <float>. The float should be a fraction, only this fraction of records will be processed.
> NUTCH-2463 - Enable sampling CrawlDB

- src/plugin/indexer-elastic/src/java/org/apache/nutch/indexwriter/elastic/ElasticIndexWriter.java
Closed #200 that included some additional changes, and included the relevant part in this PR.
> NUTCH-2399 Add support for multivalue fields on indexer-elastic

- src/java/org/apache/nutch/tools/FileDumper.java
https://issues.apache.org/jira/browse/NUTCH-2370
> fix for NUTCH-2370 contributed by msharan@usc.edu

- conf/nutch-default.xml
- src/java/org/apache/nutch/fetcher/FetcherThread.java
- restructure method handleRedirects: result of URL filters is checked early
- simplify debug logging calls
> NUTCH-2365 Fetcher to respect db.ignore.external.links.mode for redirects

- docker/Dockerfile
- upgrade base image to Ubuntu 16.04
- fetch Nutch sources via git
> NUTCH-2295 Nutch master docker container broken

- src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpBase.java
if http.accept.charset is undefined
> NUTCH-2520 Use default value for Accept-Charset

- src/java/org/apache/nutch/crawl/LinkDb.java
- src/java/org/apache/nutch/segment/SegmentMerger.java
This is mostly a cleanup of the Classes concerned with https://issues.apache.org/jira/projects/NUTCH/issues/NUTCH-2517, namely SegmentMerger and LinkDb
> NUTCH-2517 mergesegs corrupts segment data

- src/java/org/apache/nutch/util/SitemapProcessor.java
- subsitemaps from a sitemap index (contributed by Yossi Tamari)
- sitemaps referenced in robots.txt
> NUTCH-2509 Apply URL filters/normalizers also to URLs of

- src/plugin/protocol-httpclient/src/java/org/apache/nutch/protocol/httpclient/HttpResponse.java
Fix for [NUTCH-2548](https://issues.apache.org/jira/browse/NUTCH-2548)
> fix for NUTCH-2548 contributed by rustyx

- src/java/org/apache/nutch/fetcher/FetcherThread.java
This simple patch should do the trick. Tested locally and everything works as expected again.
> fix for NUTCH-2550 contributed by Hans Brende

- src/java/org/apache/nutch/crawl/Injector.java
- read directory explicitly and log all non-file entries
- exit early if no seed URL files are present
> NUTCH-2533 Injector: NullPointerException if seed URL dir contains non-file entries

- src/bin/crawl
- src/java/org/apache/nutch/crawl/WebTableReader.java
- src/java/org/apache/nutch/fetcher/FetcherJob.java
- src/java/org/apache/nutch/fetcher/FetcherReducer.java
- src/java/org/apache/nutch/indexer/CleaningJob.java
- src/java/org/apache/nutch/indexer/IndexingJob.java
and also update other Hadoop properties (deprecated / old MapReduce API)
> NUTCH-1228 Change mapred.task.timeout to mapreduce.task.timeout in fetcher

- src/java/org/apache/nutch/crawl/CrawlDb.java
- src/java/org/apache/nutch/crawl/CrawlDbMerger.java
- src/java/org/apache/nutch/crawl/CrawlDbReader.java
- src/java/org/apache/nutch/crawl/DeduplicationJob.java
- src/java/org/apache/nutch/crawl/Generator.java
- src/java/org/apache/nutch/crawl/LinkDbReader.java
- src/java/org/apache/nutch/hostdb/ReadHostDb.java
- src/java/org/apache/nutch/indexer/CleaningJob.java
- src/java/org/apache/nutch/scoring/webgraph/LinkDumper.java
- src/java/org/apache/nutch/scoring/webgraph/LinkRank.java
- src/java/org/apache/nutch/scoring/webgraph/NodeDumper.java
- src/java/org/apache/nutch/scoring/webgraph/ScoreUpdater.java
- src/java/org/apache/nutch/scoring/webgraph/WebGraph.java
- src/java/org/apache/nutch/segment/SegmentReader.java
- src/test/org/apache/nutch/crawl/TestCrawlDbFilter.java
- set job jar by calling setJarByClass
- fix compiler warnings in changed classes
> NUTCH-2569 ClassNotFoundException when running in (pseudo-)distributed mode

- src/java/org/apache/nutch/segment/SegmentReader.java
- fix type of value (CrawlDatum not Text)
> NUTCH-2571 SegmentReader -list fails to read segment

- src/java/org/apache/nutch/hostdb/UpdateHostDbReducer.java
- unwrap NutchWritable
- add logging if value class is not handled
> NUTCH-2572 HostDb: updatehostdb does not set values

- src/plugin/protocol-http/src/java/org/apache/nutch/protocol/http/HttpResponse.java
- if http.content.limit is reached skip remaining chunked content
including any headers in the trailer
> NUTCH-2562 protocol-http fails to read large chunked HTTP responses

- src/java/org/apache/nutch/fetcher/FetcherThread.java
Trivial fix: must pass error message to logger
> NUTCH-2592 Fetcher to log reason of failed fetches

- build.xml
- conf/nutch-default.xml
- src/java/org/apache/nutch/metadata/HttpHeaders.java
- src/java/org/apache/nutch/metadata/SpellCheckedMetadata.java
- src/java/org/apache/nutch/net/protocols/Response.java
- src/plugin/build.xml
- src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpBase.java
- src/plugin/protocol-htmlunit/src/java/org/apache/nutch/protocol/htmlunit/HttpResponse.java
- src/plugin/protocol-http/src/java/org/apache/nutch/protocol/http/HttpResponse.java
- src/plugin/protocol-http/src/test/conf/nutch-site-test.xml
- src/plugin/protocol-http/src/test/org/apache/nutch/protocol/http/TestBadServerResponses.java
- src/plugin/protocol-okhttp/build.xml
- src/plugin/protocol-okhttp/ivy.xml
- src/plugin/protocol-okhttp/jsp/basic-http.jsp
- src/plugin/protocol-okhttp/jsp/brokenpage.jsp
- src/plugin/protocol-okhttp/jsp/redirect301.jsp
- src/plugin/protocol-okhttp/jsp/redirect302.jsp
- src/plugin/protocol-okhttp/plugin.xml
- src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttp.java
- src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttpResponse.java
- src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/package-info.java
- src/plugin/protocol-okhttp/src/test/conf/nutch-site-test.xml
- src/plugin/protocol-okhttp/src/test/org/apache/nutch/protocol/okhttp/TestProtocolOkHttp.java
- src/plugin/urlnormalizer-basic/src/java/org/apache/nutch/net/urlnormalizer/basic/BasicURLNormalizer.java
- src/plugin/urlnormalizer-basic/src/test/org/apache/nutch/net/urlnormalizer/basic/TestBasicURLNormalizer.java
- integrates patch provided by Gerard Bouchar
- fixes sub-tasks (see commit messages)
- adds unit tests to verify that issues are solved
Note: to avoid future merge conflicts this branch/PR includes code refactorings made for NUTCH-2576.
> NUTCH-2549  protocol-http does not behave the same as browsers

- src/java/org/apache/nutch/parse/ParserChecker.java
Thanks for your contribution to [Apache Nutch](http://nutch.apache.org/)! Your help is appreciated!
- and placed in front of your commit messages
* Java source code follows [Nutch Eclipse Code Formatting rules](https://github.com/apache/nutch/blob/master/eclipse-codeformat.xml)
* Nutch is successfully built and unit tests pass by …
> NUTCH-2012: output fix

- src/java/org/apache/nutch/parse/ParserChecker.java
- inline call of passScoreAfterParsing() into loop over parses
- complete command-line help of ParserChecker
> NUTCH-2607 ParserChecker should call ScoringFilters.passScoreAfterParsing() on all parses

- src/plugin/urlfilter-validator/src/java/org/apache/nutch/urlfilter/validator/UrlValidator.java
Fix invalid assumption in URL validator
> [NUTCH-2620] Fix invalid assumption in URL validator

- src/java/org/apache/nutch/parse/ParseUtil.java
- also catch any Throwable if parser.timeout == -1 (parser is not called from ExecutorService)
- improve log message: show full class name of called parser
> NUTCH-2071 A parser failure on a single document may fail crawling job if parser.timeout=-1

- src/java/org/apache/nutch/indexer/IndexWriters.java
- src/java/org/apache/nutch/indexer/IndexerOutputFormat.java
- send deletions to all index writers as it was the case before the Exchange component has been introduced
> NUTCH-2616 Review routing of deletions by Exchange component

- src/java/org/apache/nutch/service/NutchServer.java
- src/java/org/apache/nutch/service/impl/ServiceWorker.java
- src/java/org/apache/nutch/service/model/request/ServiceConfig.java
- src/java/org/apache/nutch/service/model/response/ServiceInfo.java
- src/java/org/apache/nutch/service/resources/ServicesResource.java
- src/java/org/apache/nutch/tools/CommonCrawlDataDumper.java
- apply patch contributed Sujen Shah
- adapt to current master
> NUTCH-2152 CommonCrawl dump via Service endpoint

- src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttpResponse.java
- make sure responses are closed to avoid that connections/sockets leak
> NUTCH-2624 protocol-okhttp resource leak

- src/java/org/apache/nutch/webui/client/impl/RemoteCommand.java
> Fix for NUTCH-2641 contributed by rustyx

- build.xml
> NUTCH-2643 ant target "resolve-default" to depend on "init"

- conf/log4j.properties
- src/java/org/apache/nutch/crawl/CrawlDbReader.java
- src/java/org/apache/nutch/scoring/webgraph/NodeDumper.java
- src/java/org/apache/nutch/scoring/webgraph/WebGraph.java
- src/java/org/apache/nutch/util/ProtocolStatusStatistics.java
- need to pass filter options via job configuration into mapper
> NUTCH-2644 CrawlDbReader -dump ignores filter options

- src/java/org/apache/nutch/protocol/ProtocolFactory.java
- use object cache object to hold lock for critical block (conditional creation of plugin instance)
> NUTCH-2625 ProtocolFactory.getProtocol(url) may create multiple plugin instances

- .gitignore
- default.properties
- upgrade to 2.5.0-rc1 to address NUTCH-2669
> NUTCH-2671 Upgrade to ant ivy library

- conf/schema.xml
- add required field types to schema.xml
- tested with Nutch 1.15 and Solr 7.3.1 and 7.5.0
> NUTCH-2655 Update Solr schema.xml for Solr 7.x

- conf/nutch-default.xml
- src/java/org/apache/nutch/fetcher/QueueFeeder.java
- filter and normalize URLs in QueueFeeder if `fetcher.filter.urls` resp. `fetcher.normalize.urls` are true
> NUTCH-2627 Fetcher to optionally filter URLs

- build.xml
This issue addresses https://issues.apache.org/jira/browse/NUTCH-2698
> NUTCH-2698 Remove sonar build task from build.xml

- src/java/org/apache/nutch/crawl/DeduplicationJob.java
- add optional value "httpsOverHttp" to -compareOrder argument to prefer https:// over http:// if it comes before the "urlLength" and neither "score" nor "fetchTime" take precedence
- code improvements: remove nested loop, sort imports, add `@Override` statements where applicable
Testing with one pair of https/http duplicates:
```
% cat seeds.txt 
http://nutch.apache.org/
https://nutch.apache.org/
% nutch inject crawldb seeds.txt
...
% nutch generate crawldb/ segments
...
% nutch fetch segments/*
...
% nutch parse segments/*
...
% nutch updatedb crawldb/ segments/*
...
% nutch dedup crawldb -compareOrder httpsOverHttp,score,urlLength,fetchTime
...
Deduplication: 1 documents marked as duplicates
...
% nutch readdb crawldb/ -url https://nutch.apache.org/
URL: https://nutch.apache.org/ …
```
> NUTCH-2683 DeduplicationJob: add option to prefer https:// over http://

- src/java/org/apache/nutch/segment/SegmentReader.java
Open streams in SegmentReader using fixed UTF-8 encoding.
> NUTCH-2696 Nutch SegmentReader does not dump non-ASCII characters with Hadoop 3.x

- src/plugin/index-geoip/ivy.xml
- src/plugin/index-geoip/plugin.xml
- src/plugin/index-geoip/src/java/org/apache/nutch/indexer/geoip/GeoIPDocumentCreator.java
- src/plugin/index-geoip/src/java/org/apache/nutch/indexer/geoip/GeoIPIndexingFilter.java
- also improve handling of errors when searching for and reading GeoIP database files
- upgrade dependencies
> NUTCH-2482 index-geoip not to add null values to document fields

- src/java/org/apache/nutch/scoring/webgraph/LinkRank.java
- read output directory of link counter job to determine output file name (fail if there is none or more than one file)
- determine output codec and use it to read the output
> NUTCH-2279 LinkRank fails when using Hadoop MR output compression

- src/java/org/apache/nutch/tools/Benchmark.java
- src/plugin/index-replace/src/java/org/apache/nutch/indexer/replace/ReplaceIndexer.java
- src/plugin/parse-metatags/src/java/org/apache/nutch/parse/metatags/MetaTagsParser.java
- src/plugin/parse-tika/src/java/org/apache/nutch/parse/tika/BoilerpipeExtractorRepository.java
- src/plugin/scoring-depth/src/java/org/apache/nutch/scoring/depth/DepthScoringFilter.java
Thanks for your contribution to [Apache Nutch](http://nutch.apache.org/)! Your help is appreciated!
- and placed in front of your commit messages
* Java source code follows [Nutch Eclipse Code Formatting rules](https://github.com/apache/nutch/blob/master/eclipse-codeformat.xml)
* Nutch is successfully built and unit tests pass by …
> fix for NUTCH-2747 contributed by balashashanka

- src/plugin/indexer-solr/build.xml
- copy Solr schema.xml to runtime to include it into binary release packages
> NUTCH-2745 Solr schema.xml not shipped in binary release

- src/java/org/apache/nutch/crawl/CrawlDbReader.java
Added JSON dump capability to readdb command line tool.
> Fix for NUTCH-1863: Add JSON format dump output to readdb command

- default.properties
- src/plugin/any23/build-ivy.xml
- src/plugin/exchange-jexl/build-ivy.xml
- src/plugin/index-geoip/build-ivy.xml
- src/plugin/indexer-elastic-rest/build-ivy.xml
- src/plugin/indexer-elastic/build-ivy.xml
- src/plugin/indexer-kafka/build-ivy.xml
- src/plugin/indexer-rabbit/build-ivy.xml
- src/plugin/indexer-solr/build-ivy.xml
- src/plugin/lib-htmlunit/build-ivy.xml
- src/plugin/lib-rabbitmq/build-ivy.xml
- src/plugin/lib-selenium/build-ivy.xml
- src/plugin/parse-tika/build-ivy.xml
- src/plugin/parsefilter-naivebayes/build-ivy.xml
- src/plugin/protocol-interactiveselenium/build-ivy.xml
- src/plugin/protocol-selenium/build-ivy.xml
- src/plugin/publish-rabbitmq/build-ivy.xml
- src/plugin/scoring-similarity/build-ivy.xml
- move to https download link on repo1
> NUTCH-2761 ivy jar fails to download

- ivy/ivy.xml
Changed the dependency in ivy/ivy.xml with hadoop version as 3.1.1 as discussed.
> NUTCH-2777 - Upgrade to Hadoop 3.1

- src/plugin/indexer-solr/build-ivy.xml
- src/plugin/indexer-solr/howto_upgrade_solr.txt
- src/plugin/indexer-solr/ivy.xml
- src/plugin/indexer-solr/plugin.xml
- src/plugin/indexer-solr/src/java/org/apache/nutch/indexwriter/solr/SolrIndexWriter.java
- src/plugin/indexer-solr/src/java/org/apache/nutch/indexwriter/solr/SolrUtils.java
Upgraded the solr client to 8.5.1
Registered all the dependencies in plugin.xml
> NUTCH-2780 : Upgrade index-solr to use Solr 8.5.1

- build.xml
- default.properties
- src/java/org/apache/nutch/util/DomUtil.java
- src/plugin/build.xml
- src/plugin/parsefilter-debug/build.xml
- src/plugin/parsefilter-debug/ivy.xml
- src/plugin/parsefilter-debug/plugin.xml
- src/plugin/parsefilter-debug/src/java/org/apache/nutch/parsefilter/debug/DebugParseFilter.java
- src/plugin/parsefilter-debug/src/java/org/apache/nutch/parsefilter/debug/package-info.java
> NUTCH-2772 Debugging parse filter to show serialized DOM tree

- src/java/org/apache/nutch/tools/FreeGenerator.java
- add command-line option `-numFetchers` to FreeGenerator
- in local mode: generate one single fetch list
> NUTCH-2785 FreeGenerator: command-line option to define number of generated fetch lists

- src/java/org/apache/nutch/indexer/IndexingFiltersChecker.java
- src/java/org/apache/nutch/parse/ParserChecker.java
- src/java/org/apache/nutch/util/AbstractChecker.java
- applied Julien's patch to recent code base
- also check redirects whether they are allowed
- add command-line parameter `-checkRobotsTxt` enabling this check
> NUTCH-2002 parse and index checkers to check robots.txt

- src/java/org/apache/nutch/indexer/IndexerMapReduce.java
- src/java/org/apache/nutch/metadata/Nutch.java
- src/plugin/parse-html/src/java/org/apache/nutch/parse/html/HTMLMetaProcessor.java
- src/plugin/parse-tika/src/java/org/apache/nutch/parse/tika/HTMLMetaProcessor.java
- src/plugin/parse-tika/src/java/org/apache/nutch/parse/tika/TikaParser.java
- parse-tika: add lowercase "robots" to metadata
> NUTCH-2720 ROBOTS metatag ignored when capitalized

- src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpBase.java
1. Added the TLSv1.3 and supported cipher suites
2. Fixed indentation using eclipse-codeformat.xml
> NUTCH-2782: protocol-http / lib-http: support TLSv1.3

- .asf.yaml
- .github/pull_request_template.md
- add project description in one sentence
- add GitHub topics
- set GitHub mailing list notifications as configured before
> [NUTCH-2799] Add .asf.yaml file

- .github/workflows/master-build.yml
> NUTCH-2811 : Setup Github workflows for prs

- build.xml
- automatize download of Apache Rat jar file
- write report to build/apache-rat-report.txt
> NUTCH-2818 Fix Apache Rat task to check sources for license headers

- ivy/ivy.xml
- src/java/org/apache/nutch/crawl/CrawlDatum.java
- src/java/org/apache/nutch/crawl/CrawlDbReader.java
- src/java/org/apache/nutch/crawl/Generator.java
- src/java/org/apache/nutch/hostdb/ReadHostDb.java
- src/java/org/apache/nutch/util/JexlUtil.java
- src/plugin/exchange-jexl/src/java/org/apache/nutch/exchange/jexl/JexlExchange.java
- src/plugin/index-jexl-filter/src/java/org/apache/nutch/indexer/jexl/JexlIndexingFilter.java
This PR addresses https://issues.apache.org/jira/browse/NUTCH-2835
I did have a local test for the feed plugin which failed... can anyone reproduce this?
> NUTCH-2835 Upgrade commons-jexl from 2 --> 3

- src/bin/crawl
> [NUTCH-2834] Add possibility to setup deduplication group mode in crawl script

- ivy/ivy.xml
Trivial PR addresses https://issues.apache.org/jira/browse/NUTCH-2837
> NUTCH-2837 Update multiple dependencies

- ivy/ivy.xml
- src/java/org/apache/nutch/tools/DmozParser.java
Addresses https://issues.apache.org/jira/browse/NUTCH-2841
> NUTCH-2841 Upgrade xercesImpl dependency

- .gitignore
- build.xml
- ivy/dependency-check-ant/lib/.gitignore
This PR addresses https://issues.apache.org/jira/browse/NUTCH-2840
> NUTCH-2840 Fix 'report-vulnerabilities' ant target in build.xml

- src/java/org/apache/nutch/crawl/CrawlDatum.java
- src/java/org/apache/nutch/fetcher/Fetcher.java
- src/java/org/apache/nutch/fetcher/FetcherThread.java
- src/java/org/apache/nutch/parse/ParseOutputFormat.java
- src/java/org/apache/nutch/util/SitemapProcessor.java
- src/plugin/parsefilter-naivebayes/src/java/org/apache/nutch/parsefilter/naivebayes/Classify.java
- src/plugin/urlnormalizer-basic/src/java/org/apache/nutch/net/urlnormalizer/basic/BasicURLNormalizer.java
- Remove invalid declaration of constructor
- Use integer arithmetic instead of floating point with rounding
- Fix incorrect bracketing in calculation of hash code
- Parse integer numbers via Integer.parseInt(...)
> NUTCH-2846 Fix various bugs spotted by Spotbugs

- src/java/org/apache/nutch/tools/FileDumper.java
PR to address https://issues.apache.org/jira/browse/NUTCH-2850
I've confirmed that Spotbugs no longer flags this issue.
> NUTCH-2850 Method ignores exceptional return value

- src/plugin/urlnormalizer-protocol/data/protocols.txt
- src/plugin/urlnormalizer-protocol/src/java/org/apache/nutch/net/urlnormalizer/protocol/ProtocolURLNormalizer.java
- src/plugin/urlnormalizer-protocol/src/test/org/apache/nutch/net/urlnormalizer/protocol/TestProtocolURLNormalizer.java
... when reading invalid line in configuration file
- log invalid line and skip over it
- more verbose logging which configuration file is read
> NUTCH-2868 urlnormalizer-protocol fails with StringIndexOutOfBoundsException

- docker/Dockerfile
Addresses https://issues.apache.org/jira/browse/NUTCH-2881
> NUTCH-2881 bug in 'nutch' symlink in docker container

- conf/log4j.properties
- src/java/org/apache/nutch/webui/NutchUiApplication.java
Addresses https://issues.apache.org/jira/browse/NUTCH-2882
> NUTCH-2882 Configure NutchUiServer for DEPLOYMENT and improve logging

- src/plugin/any23/howto_upgrade_any23.txt
- src/plugin/any23/ivy.xml
- src/plugin/any23/plugin.xml
This PR addresses https://issues.apache.org/jira/browse/NUTCH-2892
> NUTCH-2892 Upgrade to Any23 2.5

- ivy/ivy.xml
- src/java/org/apache/nutch/tools/warc/WARCExporter.java
(PR based on patch contributed by Markus Jelsma, see [NUTCH-2865](https://issues.apache.org/jira/browse/NUTCH-2865))
> NUTCH-2865 WARC exporter support for metadata and dropping empty responses

- conf/nutch-default.xml
- src/java/org/apache/nutch/hostdb/AbstractCrawlDatumProcessor.java
- src/java/org/apache/nutch/hostdb/CrawlDatumProcessor.java
- src/java/org/apache/nutch/hostdb/FetchOverdueCrawlDatumProcessor.java
- src/java/org/apache/nutch/hostdb/UpdateHostDb.java
- src/java/org/apache/nutch/hostdb/UpdateHostDbReducer.java
(PR based on patch contributed by Markus Jelsma)
> NUTCH-2867 Support for custom HostDb aggregators

- src/java/org/apache/nutch/fetcher/Fetcher.java
Fix for [NUTCH-2911](https://issues.apache.org/jira/browse/NUTCH-2911)
Changes made : Added a wrapper try-finally block for FetcherRun.run() and called cleanup()
> fix for NUTCH-2911 contributed by prakharchaube

- conf/nutch-default.xml
... and update the description of various protocol-related configuration properties
> NUTCH-2808 Document side effects of ignoring robots.txt

- src/plugin/indexer-elastic/src/java/org/apache/nutch/indexwriter/elastic/ElasticIndexWriter.java
- apply patch contributed by Markus Jelsma
- fix class imports
> NUTCH-2953 Indexer Elastic to ignore SSL issues

- src/plugin/indexer-solr/schema.xml
- add fall-back field definitions for unknown index fields
- update comments and descriptions
- fix indentation
> NUTCH-2957 indexer-solr / Solr schema.xml: fall-back field definition

- src/java/org/apache/nutch/crawl/CrawlDbReader.java
- configure CSV and JSON LineRecordWriters to compress the output files according to the configuration
> NUTCH-2795 CrawlDbReader: compress CrawlDb dumps if configured

- src/plugin/parse-html/src/java/org/apache/nutch/parse/html/DOMContentUtils.java
- src/plugin/parse-html/src/test/org/apache/nutch/parse/html/TestDOMContentUtils.java
- src/plugin/parse-tika/src/java/org/apache/nutch/parse/tika/DOMContentUtils.java
- src/plugin/parse-tika/src/test/org/apache/nutch/parse/tika/TestDOMContentUtils.java
- fix detection of nofollow in multi-valued rel attributes in parse-html and parse-tika
- add unit tests to prove solution
> NUTCH-2634 Some links marked as "nofollow" are followed anyway

- src/java/org/apache/nutch/fetcher/FetchItemQueues.java
If QueueFeeder is still alive, also block queues which are empty right now.
> NUTCH-2992 Fetcher: always block fetch queues when exceptions threshold is reached

- conf/nutch-default.xml
- src/plugin/scoring-depth/src/java/org/apache/nutch/scoring/depth/DepthScoringFilter.java
- apply patch contributed by Markus Jelsma
> NUTCH-2993 ScoringDepth plugin to skip depth check based on URL Pattern

- src/plugin/protocol-http/src/java/org/apache/nutch/protocol/http/HttpResponse.java
Thanks for your contribution to [Apache Nutch](https://nutch.apache.org/)! Your help is appreciated!
- and placed in front of your commit messages surrounded by square brackets (`[NUTCH-XXXX] Issue or pull request title`)
* Java source code follows [Nutch Eclipse Code Formatting …
> NUTCH-3004

- src/java/org/apache/nutch/indexer/IndexingFiltersChecker.java
- src/java/org/apache/nutch/net/URLFilterChecker.java
- src/java/org/apache/nutch/net/URLNormalizerChecker.java
- src/java/org/apache/nutch/parse/ParserChecker.java
- src/java/org/apache/nutch/util/AbstractChecker.java
Remove all calls of System.exit(...) in methods except main(args) of various "checker" tools and replace by return values passed to main().
> NUTCH-2852 SpotBugs: Method invokes System.exit(...)

- src/java/org/apache/nutch/fetcher/Fetcher.java
- src/java/org/apache/nutch/parse/ParseSegment.java
- remove code blocks (else clauses) unneeded and containing impossible casts
> NUTCH-3007 Fix impossible casts

- src/java/org/apache/nutch/crawl/Injector.java
- add counter urls_injected_unique
- improve log messages reporting the counts of injected/merged URLs
> NUTCH-3010 Injector: count unique number of injected URLs

- ivy/ivy.xml
- src/plugin/language-identifier/ivy.xml
- src/plugin/language-identifier/plugin.xml
- src/plugin/parse-tika/ivy.xml
- src/plugin/parse-tika/plugin.xml
Thanks for your contribution to [Apache Nutch](https://nutch.apache.org/)! Your help is appreciated!
- and placed in front of your commit messages surrounded by square brackets (`[NUTCH-XXXX] Issue or pull request title`)
* Java source code follows [Nutch Eclipse Code Formatting …
> NUTCH-3019 -- update Tika to 2.9.1

- src/bin/crawl
Show --dedup-group instead of -dedup-group which have lead to misunderstanding output
> [NUTCH-2834] Update crawl documentation / Fix #557

- docker/Dockerfile
> Revert "Update Dockerfile / JAVA_HOME"

- .github/workflows/master-build.yml
Addresses https://issues.apache.org/jira/browse/NUTCH-3054
> NUTCH-3054 Address deprecation of Node16 for all GitHub Actions

- src/java/org/apache/nutch/net/URLExemptionFilters.java
- src/plugin/urlfilter-ignoreexempt/README.md
- src/plugin/urlfilter-ignoreexempt/src/java/org/apache/nutch/urlfilter/ignoreexempt/ExemptionUrlFilter.java
PR to address https://issues.apache.org/jira/browse/NUTCH-3041
> NUTCH-3041 Address confusing logging in o.a.n.net.URLExemptionFilters

- src/plugin/indexer-elastic/ivy.xml
- src/plugin/indexer-elastic/plugin.xml
https://issues.apache.org/jira/browse/NUTCH-3097
> NUTCH-3097 fixed dependencies for indexer-elastic

- src/java/org/apache/nutch/util/SitemapProcessor.java
Verify the sitemap additional values added from a sitemap to CrawlDB by SitemapProcessor: priority, modification time and change frequency.
- use default priority if priority <= 0.0 (a CrawlDatum with score 0.0 is not eligible for fetch)
- ensure that the fetch interval (from change frequency) is within db.fetch.schedule.adaptive.min_interval and db.fetch.schedule.adaptive.max_interval
- ignore last-modified times in the future
> NUTCH-2976 SitemapProcessor: verify sitemap values added from sitemap to CrawlDB
