src/java/org/apache/nutch/crawl/GeneratorJob.java
src/test/nutch-site.xml
src/test/org/apache/nutch/fetcher/TestFetcher.java

Hi Folks,
This pull request formalizes the contribution from Adnane B. over on [NUTCH-2222](https://issues.apache.org/jira/browse/NUTCH-2222). I am not sure that this is catching the bug however and it seems like the bug only rears it's head when we use a persistent datastore. 
Right now this patch uses the MemStore implementation which is what we agreed tests would be like. I think we need to do add to the tests in order to have a persistent datastore setup and that data is persisted into the datastore.

NUTCH-2222 re-fetch deletes all metadata except _csh_ and _rs_

---

src/java/org/apache/nutch/tools/CommonCrawlDataDumper.java
src/java/org/apache/nutch/tools/CommonCrawlFormat.java

+ Reads all parts of segments
+ writes single document per dump file
1. Lists all files insides segments and selects all the parts matching to pattern part-[0-9]{5} under the content directory. 
2. CommonCrawlFormat implementation for "JACKSON" type does not clear state, instead it keeps appending documents. This fix uses a new instance for each document (actually it was hard to resolve the state issue because of too many options such as compressing and archiving).

NUTCH-2250 : CommonCrawlDumper : Invalid format and skipped parts

---

src/java/org/apache/nutch/tools/AbstractCommonCrawlFormat.java
src/java/org/apache/nutch/tools/CommonCrawlDataDumper.java
src/java/org/apache/nutch/tools/CommonCrawlFormat.java

This PR enhances the CommonCrawlDumper with an optional CLI argument to accept linkdb path.
When this option is supplied, an additional field called "inlinks" will be included in the dump files.
We enhanced this as part of MEMEX crawler for analysing crawl link graph from dump files we believe this may be useful for other nutch users as well.
CC @sujen1412 @chrismattmann

Option to include inlinks in commonscrawl dump

---

docker/hbase/Dockerfile

When running a inject, throws exception
```
hduser@028ce34179ee:/opt/nutch$ bin/nutch inject urls/seed.txt 
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /opt/nutch/logs/hadoop.log (No such file or directory)
at java.io.FileOutputStream.open(Native Method)
at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:223)
at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172) …
```

Nutch requires a logs folder to run exception free

---

conf/parse-plugins.xml
src/plugin/build.xml
src/plugin/parse-css/build.xml
src/plugin/parse-css/ivy.xml
src/plugin/parse-css/plugin.xml
src/plugin/parse-css/src/java/org/apache/nutch/parse/css/CssParser.java
src/plugin/parse-css/src/test/org/apache/nutch/parse/css/TestCssParser.java

As described on JIRA:
This plugin allows for collecting uri links from CSS (stylesheets). This is useful for collecting parent stylesheets, fonts, and images needed to display web pages as intended.
Parsed Outlinks do not have associated anchors, and no additional text/content is parsed from the stylesheet.

NUTCH-2248 CSS parser plugin

---

ivy/ivysettings.xml

Adding restlet as a resolver to the default chain fixes missing org.restlet.jee when building with gora-solr

NUTCH-2112 Missing restlet resolver when building with gora-solr

---

build.xml
default.properties

Created javadoc.link.solr instead of javadoc.link.lucene and pointed to solrj api documentation since its used at Nutch.

NUTCH-2266 Dead link in build.xml for javadoc is fixed.

---

default.properties

This issue partly addresses https://issues.apache.org/jira/browse/NUTCH-2089
There are lots of Javadoc warnings and a few errors

NUTCH-2089 Move Nutch to compile on JDK 8

---

docker/cassandra/bin/restart.sh
docker/cassandra/bin/start.sh
docker/cassandra/bin/stop.sh

"Bad substitution" error appears when running the following docker scripts:
docker/cassandra/bin/start.sh
docker/cassandra/bin/stop.sh
docker/cassandra/bin/restart.sh
e.g.
./bin/start.sh: 18: ./bin/start.sh: Bad substitution

NUTCH-2283 Fix bad substitution bash error for cassandra docker scripts

---

build.xml
default.properties
ivy/ivy.xml
src/plugin/indexer-elastic/ivy.xml
src/plugin/indexer-elastic/plugin.xml
src/plugin/indexer-elastic/src/java/org/apache/nutch/indexwriter/elastic/ElasticIndexWriter.java
src/plugin/indexer-solr/ivy.xml
src/plugin/indexer-solr/plugin.xml
src/plugin/parsefilter-naivebayes/ivy.xml
src/plugin/parsefilter-naivebayes/plugin.xml
src/plugin/scoring-similarity/build.xml
src/plugin/scoring-similarity/ivy.xml
src/plugin/scoring-similarity/plugin.xml
src/plugin/scoring-similarity/src/java/org/apache/nutch/scoring/similarity/util/LuceneAnalyzerUtil.java
src/plugin/scoring-similarity/src/java/org/apache/nutch/scoring/similarity/util/LuceneTokenizer.java

Upgrade Elasticsearch and Lucene dependencies, which, in turn, requires updates to Guava and Hadoop dependencies:
- Elasticsearch 1.4.1 -> Elasticsearch 2.3.3
- Lucene 4.10.2 -> 5.5.0
- Guava 16.0.1 -> Guava 18.0
- Hadoop 2.4.0 -> 2.7.2

fix for NUTCH-2234 and NUTCH-2236

---

src/plugin/indexer-solr/src/java/org/apache/nutch/indexwriter/solr/SolrUtils.java

Explicitly pass in an instance of SystemDefaultHttpClient to CloudSolrClient, otherwise SolrJ will use a default implementation of CloseableHttpClient, which is not present in the HttpClient and HttpCore JARs in Hadoop < 2.8 (see https://issues.apache.org/jira/browse/SOLR-7948 and https://issues.apache.org/jira/browse/HADOOP-12767).

NUTCH-2267 - Solr and Hadoop JAR mismatch

---

conf/httpclient-auth.xml.template
src/plugin/protocol-httpclient/src/java/org/apache/nutch/protocol/httpclient/Http.java
src/plugin/protocol-httpclient/src/java/org/apache/nutch/protocol/httpclient/HttpFormAuthConfigurer.java
src/plugin/protocol-httpclient/src/java/org/apache/nutch/protocol/httpclient/HttpFormAuthentication.java

Fix the [NUTCH-2280](https://issues.apache.org/jira/browse/NUTCH-2280).
When a HTTP post receives session cookie from server, it might hit an issue when the server has a domain name set as ".domain.com". The "." at beginning will cause HttpClient reject this cookie.

NUTCH-2280 fix the cookie policy issue in post form authentication

---

conf/nutch-default.xml
src/java/org/apache/nutch/fetcher/FetcherThread.java
src/java/org/apache/nutch/parse/ParseSegment.java
src/java/org/apache/nutch/protocol/Protocol.java
src/java/org/apache/nutch/protocol/RobotRulesParser.java
src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpBase.java
src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpRobotRulesParser.java
src/plugin/protocol-file/src/java/org/apache/nutch/protocol/file/File.java
src/plugin/protocol-ftp/src/java/org/apache/nutch/protocol/ftp/Ftp.java
src/plugin/protocol-ftp/src/java/org/apache/nutch/protocol/ftp/FtpRobotRulesParser.java

If the property fetcher.store.robotstxt is set to true, Fetcher saves the robots.txt
response (URL and Content including HTTP protocol status and metadata) in the
segment (subfolder content/). It does not add a fetch datum, simply because this
avoids that the robots.txt URL slips into CrawlDb or gets indexed. The robots.txt
can then be retrieved from the segment, e.g., by
```
bin/nutch fetch -Dfetcher.store.robotstxt=true -Dfetcher.store.content=true ...path_to_segment
bin/nutch readseg -dump ...path_to_segment ...path_to_dump
cat ...path_to_dump/dump
...
URL:: http://nutch.apache.org/robots.txt
Content::
Version: -1
url: http://nutch.apache.org/robots.txt
base: http://nutch.apache.org/robots.txt
contentType: text/html
metadata: nutch.fetch.time=1471612087645 Server=Apache/2.4.7 (Ubuntu) …
```

NUTCH-2300 Fetcher to optionally save robots.txt

---

src/plugin/urlnormalizer-basic/src/java/org/apache/nutch/net/urlnormalizer/basic/BasicURLNormalizer.java
src/plugin/urlnormalizer-basic/src/test/org/apache/nutch/net/urlnormalizer/basic/TestBasicURLNormalizer.java

- check whether URL.getAuthority() returns null
- recompose URLs without authority with empty authority/host

NUTCH-2349 urlnormalizer-basic: NPE for URLs without authority

---

build.xml
conf/log4j.properties
conf/nutch-default.xml
ivy/ivy.xml
src/plugin/build.xml
src/plugin/indexer-elastic-rest/build-ivy.xml
src/plugin/indexer-elastic-rest/build.xml
src/plugin/indexer-elastic-rest/howto_upgrade_es.txt
src/plugin/indexer-elastic-rest/ivy.xml
src/plugin/indexer-elastic-rest/plugin.xml
src/plugin/indexer-elastic-rest/src/java/org/apache/nutch/indexwriter/elasticrest/ElasticRestConstants.java
src/plugin/indexer-elastic-rest/src/java/org/apache/nutch/indexwriter/elasticrest/ElasticRestIndexWriter.java
src/plugin/indexer-elastic-rest/src/java/org/apache/nutch/indexwriter/elasticrest/package-info.java

Open Elasticsearch to the option of REST-based indexing, via another indexing plugin implemented using Jest, allowing the use of https.

Fix for NUTCH-2296: Elasticsearch Indexing Over Rest

---

src/java/org/apache/nutch/crawl/Injector.java

Restore the default behavior before NUTCH-1712 and make the usage of URL filters and normalizers configurable via command-line options:
- `-filterNormalizeAll` : normalize and filter all URLs including the URLs of existing CrawlDb records
- `-noNormalize` and `-noFilter` : do not normalize resp. filter any URLs (new injected or existing ones)

NUTCH-2335 Injector not to filter and normalize existing items/URLs in CrawlDb

---

build.xml
conf/nutch-default.xml
src/plugin/build.xml
src/plugin/indexer-rabbit/build-ivy.xml
src/plugin/indexer-rabbit/build.xml
src/plugin/indexer-rabbit/ivy.xml
src/plugin/indexer-rabbit/plugin.xml
src/plugin/indexer-rabbit/src/java/org/apache/nutch/indexwriter/rabbit/RabbitDocument.java
src/plugin/indexer-rabbit/src/java/org/apache/nutch/indexwriter/rabbit/RabbitIndexWriter.java
src/plugin/indexer-rabbit/src/java/org/apache/nutch/indexwriter/rabbit/RabbitMQConstants.java
src/plugin/indexer-rabbit/src/java/org/apache/nutch/indexwriter/rabbit/RabbitMessage.java

An indexer for RabbitMQ is for sending crawled documents to a queue into a server of RabbitMQ. Just like solr-indexer or elastic-indexer do. This indexer send a lot of documents to RabbitMQ, not one by one, according to rabbitmq.indexer.commit.size value.

fix for NUTCH-2333 contributed by r0ann3l

---

src/bin/crawl

This makes the seed argument optional and is an alternative to the solution proposed in [https://issues.apache.org/jira/browse/NUTCH-2046]. The latter is also acceptable and has the advantage of not breaking compatibility.

Fix for NUTCH-2046 contributed by jnioche

---

src/java/org/apache/nutch/service/model/request/SeedUrl.java
src/java/org/apache/nutch/service/resources/SeedResource.java
src/java/org/apache/nutch/webui/model/SeedUrl.java

This PR adds the possibility of attaching metadata to the seed file created using the REST API as showed on https://issues.apache.org/jira/browse/NUTCH-2353, the supported syntax is:
```json
{
"name":"name-of-seedlist", 
"seedUrls":[
{
"url" : "http://example.com",
"metadata" : {
"key1" : "value1",
"key2" : "value2",
"key3" : "value3"
}
}
]
}
```
Also the old syntax is supported:
```json
{
"name":"name-of-seedlist", 
"seedUrls":["http://www.example.com", "http://www.example1.com"]
}
```

Fix for NUTCH-2353 contributed by jorgelbg

---

conf/nutch-default.xml
src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpBase.java
src/plugin/protocol-http/src/java/org/apache/nutch/protocol/http/HttpResponse.java
src/plugin/protocol-httpclient/src/java/org/apache/nutch/protocol/httpclient/Http.java

- Accept, Accept-Language and Accept-Charset are configured and used the
same way for both protocol-http and protocol-httpclient
- a space as value will unset these header fields (not sent in request)
I've tried to overwrite the default by an empty value but that's not possible with the Hadoop configuration mechanism. Of course, one could configure instead `*` as "Accept-Language" or "Accept-Charset" (resp. `*/*` as "Accept" content type) but that will unnecessarily blow up the HTTP requests.

NUTCH-2376 Improve configurability of HTTP Accept* header fields

---

build.xml
conf/nutch-default.xml
ivy/ivy.xml
ivy/mvn.template
src/java/org/apache/nutch/indexer/CleaningJob.java
src/java/org/apache/nutch/metadata/Metadata.java
src/plugin/indexer-hbase/src/java/org/apache/nutch/indexwriter/hbase/HBaseIndexWriter.java
src/plugin/indexer-hbase/src/java/org/apache/nutch/indexwriter/hbase/HBaseMappingReader.java
src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpBase.java
src/plugin/urlnormalizer-basic/src/java/org/apache/nutch/net/urlnormalizer/basic/BasicURLNormalizer.java
src/plugin/urlnormalizer-basic/src/test/org/apache/nutch/net/urlnormalizer/basic/TestBasicURLNormalizer.java

An index writer for HBase like index writer for Solr, ElasticSearch etc. Expected HBase table description and NutchDocument to HBase mapping is read using a _indexer-solr_ alike mapping file and write NutchDocument fields into the table of a HBase server.
TODO: Functionality to send and set kerberos authentication configuration for secure hdfs

NUTCH-2373 Index writer plugin for hbase implemented

---

src/bin/crawl

During each iteration, after generating, fetching, parsing and updating the current batch into DB, the indexer is supposed to index the current batch too. But its indexing all currently.
```shell
__bin_nutch index $commonOptions -D solr.server.url=$SOLRURL -all -crawlId "$CRAWL_ID"
```
It should be like below i guess -
```shell
__bin_nutch index $commonOptions -D solr.server.url=$SOLRURL $batchId -crawlId "$CRAWL_ID"
```

NUTCH-2388 bin/crawl indexing only webpages of current batch instead of all

---

src/java/org/apache/nutch/crawl/MD5Signature.java

[NUTCH-2391](https://issues.apache.org/jira/browse/NUTCH-2391): use URL for MD5 digest as fall-back if content is empty, i.e., content length is zero (contributed by David Johnson)

NUTCH-2391 Spurious Duplications for MD5

---

src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpRobotRulesParser.java

do not use original URL (http://example.com/robots.txt) to store both
redirect response (HTTP 301) and response of redirect target
See also commoncrawl/nutch#4.

NUTCH-2398: Save content of redirected robots.txt under redirect target URL

---

src/plugin/protocol-selenium/README.md

The Nutch Selenium documentation states that PhantomJS can be used as `phantomJS` for `selenium.driver`. The correct value would be `phantomjs` according to https://github.com/apache/nutch/blob/master/src/plugin/lib-selenium/src/java/org/apache/nutch/protocol/selenium/HttpWebClient.java#L124

NUTCH-2403: Fix spelling of phantomJS configuration

---

src/java/org/apache/nutch/crawl/CrawlDb.java

- use unparsed segments to update status in CrawlDb
- but log if unparsed segment is detected (priorly unparsed segments where logged and skipped)

NUTCH-2408 CrawlDb: allow update from unparsed segments

---

conf/nutch-default.xml
src/plugin/parse-html/src/java/org/apache/nutch/parse/html/DOMContentUtils.java
src/plugin/parse-tika/src/java/org/apache/nutch/parse/tika/DOMContentUtils.java

New configuration for HTML parser to keep the HTML nodes where outlinks are found, into their metadata.

Nutch 2433 - New configuration for HTML parser to keep the HTML nodes in outlinks metadata

---

src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpBase.java

(And do not append a slash to http.agent.name.)

NUTCH-2448: Treat white-space http.agent.version as empty.

---

build.xml
conf/nutch-default.xml
default.properties
src/java/org/apache/nutch/crawl/CrawlDatum.java
src/java/org/apache/nutch/crawl/CrawlDb.java
src/java/org/apache/nutch/crawl/CrawlDbFilter.java
src/java/org/apache/nutch/crawl/CrawlDbReducer.java
src/java/org/apache/nutch/scoring/ScoringFilter.java
src/java/org/apache/nutch/scoring/ScoringFilters.java
src/plugin/build.xml
src/plugin/scoring-orphan/build.xml
src/plugin/scoring-orphan/ivy.xml
src/plugin/scoring-orphan/plugin.xml
src/plugin/scoring-orphan/src/java/org/apache/nutch/scoring/orphan/OrphanScoringFilter.java
src/plugin/scoring-orphan/src/java/org/apache/nutch/scoring/orphan/package-info.java
src/plugin/scoring-orphan/src/test/org/apache/nutch/scoring/orphan/TestOrphanScoringFilter.java
src/test/org/apache/nutch/crawl/TestCrawlDbStates.java

- apply Markus Jelsma's latest patch, 2016-06-30
- add method orphanedScore(Text, CrawlDatum) to ScoringFilter interface
- complete unit tests for CrawlDb update

NUTCH-1932 Automatically remove orphaned pages

---

src/plugin/parse-html/src/java/org/apache/nutch/parse/html/DOMContentUtils.java
src/plugin/parse-html/src/test/org/apache/nutch/parse/html/TestDOMContentUtils.java
src/plugin/parse-tika/src/java/org/apache/nutch/parse/tika/DOMContentUtils.java
src/plugin/parse-tika/src/test/org/apache/nutch/tika/TestDOMContentUtils.java

Add support for the `video`/`source` tag in the outlink extractor of the `parse-html` and `parse-tika` plugin.

NUTCH-2443 add source tag to the parse-html/tika outlink extractor

---

build.xml
src/plugin/protocol-interactiveselenium/src/java/org/apache/nutch/protocol/interactiveselenium/HttpResponse.java
src/plugin/protocol-interactiveselenium/src/java/org/apache/nutch/protocol/interactiveselenium/handlers/DefalultMultiInteractionHandler.java
src/plugin/protocol-interactiveselenium/src/java/org/apache/nutch/protocol/interactiveselenium/handlers/DefaultClickAllAjaxLinksHandler.java
src/plugin/protocol-interactiveselenium/src/java/org/apache/nutch/protocol/interactiveselenium/handlers/DefaultHandler.java
src/plugin/protocol-interactiveselenium/src/java/org/apache/nutch/protocol/interactiveselenium/handlers/InteractiveSeleniumHandler.java

This is the fix of Eclipse for the latest master. It was broken because of : incorrect class paths(build.xml) and an incorrect package usage in InteractiveSeleniumHandler.

fix of NUTCH-2465 broken Eclipse project. Classpaths and wrong packages of interactiveselenium.handlers

---

src/plugin/headings/ivy.xml
src/plugin/headings/src/java/org/apache/nutch/parse/headings/HeadingsParseFilter.java
src/plugin/headings/src/test/org/apache/nutch/parse/headings/TestHeadingsParseFilter.java

As suggested by @sebastian-nagel refactored the `getNodeValue` method to use `NodeWalker` iterators. This allows traversing the entire DOM tree in case of nested nodes as explained on the issue. Added a test case for this issue as well.

Fix for NUTCH-2464 get textual content from nested heading nodes

---

ivy/ivy.xml
src/java/org/apache/nutch/crawl/CrawlDbReader.java

- add quantiles:
```
score quantile 0.01:    -0.002406878347319667
score quantile 0.05:    0.0
score quantile 0.1:     0.0
score quantile 0.2:     0.0
score quantile 0.25:    0.0
score quantile 0.3:     0.0
score quantile 0.4:     0.0
score quantile 0.5:     0.0
score quantile 0.6:     1.3519638927815378E-7
score quantile 0.7:     1.7516442206153347E-5
score quantile 0.75:    7.380095048071454E-5
score quantile 0.8:     1.8289990560181772E-4
score quantile 0.9:     7.733948471002675E-4
score quantile 0.95:    0.00450346029134317
score quantile 0.99:    0.2702074978807236
min score:      -0.007237845566123724
avg score:      0.010340072900048684
max score:      70.0
```
- improves precision of score min/max/average
(represent score by float instead of long * 1000)

NUTCH-2470 CrawlDbReader -stats to show quantiles of score

---

conf/nutch-default.xml
src/plugin/language-identifier/src/java/org/apache/nutch/analysis/lang/LanguageIndexingFilter.java

Added property lang.index.languages. If exists and is not empty, it is treated as a comma-separated list of languages to index. A document in another language will not be indexed.
"unknown" is a valid language code.

NUTCH-2414 - Allow LanguageIndexingFilter to actually filter documents by language

---

src/plugin/indexer-elastic-rest/plugin.xml

When trying to index into Elasticsearch using indexer-elastic-rest the following error is being thrown:
```
Exception in thread "main" java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/apache/nutch/plugin/PluginClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:418)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
at …
```

fix for NUTCH-2473 Remove broken slf4j dependecy from indexer-elastic-rest

---

src/java/org/apache/nutch/crawl/CrawlDbReader.java

- replace CrawlDbStatCombiner by CrawlDbStatReducer and ensure
that data is properly processed independently whether and
how often combiner is called
- simplify calculation of minimum and maximum
Tested in local mode. Large scale test on multi-billion CrawlDb (distributed mode) is scheduled. I'll report the results after the weekend.

NUTCH-2474 CrawlDbReader -stats fails with ClassCastException

---

ivy/ivy.xml

and exclude transitive dependency to tika-core to avoid that Tika version requested as direct dependency is evicted.

NUTCH-2480 Upgrade crawler-commons dependency to 0.9

---

src/plugin/index-geoip/ivy.xml
src/plugin/index-geoip/plugin.xml

- upgrade to recent version 2.10.0
- as there are no unit tests, tested with indexchecker:
```
$ bin/nutch indexchecker -Dstore.ip.address=true -Dindex.geoip.usage=cityDatabase \
-Dplugin.includes="protocol-http|parse-html|index-(basic|geoip)" http://www.example.com/
fetching: http://www.example.com/
robots.txt whitelist not configured.
parsing: http://www.example.com/
contentType: text/html
countryIsoCode :        US
postalCode :    02061
title : Example Domain
accRadius :     50
content :       Example Domain
Example Domain
This domain is established to be used for illustrative examples in doc
cityName :      Norwell
digest :        09b9c392dc1f6e914cea287cb6be34b0
host :  www.example.com
id :    http://www.example.com/
continentCode : NA
cityGeoNameId : 4945936
ip :    93.184.216.34 …
```

NUTCH-2362 Upgrade MaxMind GeoIP version in index-geoip

---

src/java/org/apache/nutch/util/DomUtil.java
src/plugin/parse-html/src/java/org/apache/nutch/parse/html/DOMContentUtils.java
src/plugin/parse-html/src/java/org/apache/nutch/parse/html/HtmlParser.java
src/plugin/parse-html/src/test/org/apache/nutch/parse/html/TestHtmlParser.java
src/plugin/parse-tika/src/java/org/apache/nutch/parse/tika/DOMContentUtils.java
src/plugin/parse-tika/src/java/org/apache/nutch/parse/tika/TikaParser.java
src/plugin/parse-tika/src/test/org/apache/nutch/tika/TestHtmlParser.java

- fix parse-html: base href is resolved with fetched URL
- fix parse-tika: because href attribute of base element dropped in DOM, need to call `tikamd.get("Content-Location")`
- add unit test
- port HTML parser test from parse-html to parse-tika
- add method to DomUtil which prints DocumentFragment

NUTCH-2478 parser resolve base url

---

ivy/ivy.xml

- exclude dependency for webarchive-commons: no classes requiring JSON are used
- exclude dependency for wicket-bootstrap-extensions (transitive dep via closure-compiler):
only one class is used from wicket-bootstrap-extensions which isn't related to JavaScript or JSON

NUTCH-2483 Remove/replace indirect dependencies to org.json

---

src/plugin/mimetype-filter/src/java/org/apache/nutch/indexer/filter/MimeTypeIndexingFilter.java

Fixes `Note: src/plugin/mimetype-filter/src/java/org/apache/nutch/indexer/filter/MimeTypeIndexingFilter.java uses unchecked or unsafe operations.`

NUTCH-2486: Fix unchecked / unsafe compiler warning

---

src/java/org/apache/nutch/crawl/Generator.java
src/java/org/apache/nutch/metadata/Nutch.java

The recently introduced functionality allows usage of hostdb in generator. However the functionality didn't work when Generator is called from REST API server. This fix introduces hostdb for REST API.

fix for NUTCH-2454 REST API fix for usage of hostdb in generator

---

src/java/org/apache/nutch/util/SitemapProcessor.java

This fixes processing of sitemap index files by removing a unnecessary conditional.
Before:
```bash
$ echo "https://filialen.migros.ch/sitemap.xml" > sitemaps.txt && bin/nutch sitemap crawldata -sitemapUrls sitemaps.txt
SitemapProcessor: sitemap urls dir: sitemaps.txt
SitemapProcessor: Starting at 2018-01-02 22:44:58
robots.txt whitelist not configured.
SitemapProcessor: Total records rejected by filters: 0
SitemapProcessor: Total sitemaps from HostDb: 0
SitemapProcessor: Total sitemaps from seed urls: 1
SitemapProcessor: Total failed sitemap fetches: 0
SitemapProcessor: Total new sitemap entries added: 0
SitemapProcessor: Finished at 2018-01-02 22:45:02, elapsed: 00:00:03
````
After:
```bash
$ echo "https://filialen.migros.ch/sitemap.xml" > sitemaps.txt && bin/nutch sitemap crawldata …
```

fix for NUTCH-2490 Fix sitemap index file processing

---

src/java/org/apache/nutch/indexer/IndexingJob.java

There was an extra if condition in run( ) method where it sets linkdb path. It is evident when we use nutch REST api.
https://github.com/apache/nutch/blob/master/src/java/org/apache/nutch/indexer/IndexingJob.java#L272

Bug in setting default linkdb path

---

src/bin/crawl

While using the crawler script with the sitemap processing feature introduced in #271 I encountered some performance issues when working with large sitemaps.
Therefore one should be able to specify if sitemap processing based on HostDB should take place and if so how frequently it should be done.

NUTCH-2493: Add new parameter to crawler script to configure sitemap processing frequency

---

src/java/org/apache/nutch/crawl/Generator.java

When max count == 0 the reducer ignores hostdb condition because of  if (maxCount > 0). The fix adds the condition, but add it as explicit statement to save the ruining time.

fix for NUTCH-2461 generate with maxcount equals 0

---

src/plugin/indexer-elastic-rest/src/java/org/apache/nutch/indexwriter/elasticrest/ElasticRestIndexWriter.java

This bug was introduced in https://github.com/apache/nutch/commit/160758023e3de83894ae4fe654c17fde62aba50e#diff-408fd2f17bc9791dcbf531ffe6574a6a

fix for NUTCH-2499: Filter duplicated field values when indexing using Elastic REST indexer

---

conf/nutch-default.xml

This is a small documentation fix since the description of `http.proxy.exception.list` is misleading. Only hosts can be defined as you can see here: https://github.com/apache/nutch/blob/master/src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpBase.java#L370

fix for NUTCH-2508 contributed by mfeltscher

---

src/plugin/scoring-similarity/ivy.xml
src/plugin/scoring-similarity/plugin.xml
src/plugin/scoring-similarity/src/java/org/apache/nutch/scoring/similarity/util/LuceneAnalyzerUtil.java
src/plugin/scoring-similarity/src/java/org/apache/nutch/scoring/similarity/util/LuceneTokenizer.java

Upgraded lucene-analyzers-common from 5.5.0 to 6.4.1 in order to resolve conflict in Eclipse.

NUTCH-2489: Dependency collision with lucene-analyzers-common in scoring-similarity plugin

---

conf/nutch-default.xml
src/java/org/apache/nutch/crawl/CrawlDbReader.java

by property `db.stats.score.quantiles`, e.g., show only quartiles:
```
$NUTCH_HOME/bin/nutch readdb -Ddb.stats.score.quantiles=.25,.5,.75 .../crawldb -stats
...
score quantile 0.25:    0.0
score quantile 0.5:     7.949125720188022E-4
score quantile 0.75:    0.06881623715162277
...
```

NUTCH-2534 CrawlDbReader -stats: make score quantiles configurable

---

src/plugin/protocol-http/src/java/org/apache/nutch/protocol/http/HttpResponse.java

- apply Markus' patch
- if reconnect fails throw HTTPException
This solution (work-around) has been tested in production.

NUTCH-2447 Work-around SSLProtocolException: handshake alert: unrecognized_name

---

src/java/org/apache/nutch/indexer/IndexingFiltersChecker.java
src/java/org/apache/nutch/parse/ParserChecker.java
src/java/org/apache/nutch/util/AbstractChecker.java

- let ParserChecker inherit from AbstractChecker
(URLs are now read from stdin resp. parsechecker listens on the given port)
- sync run() method of classes ParserChecker and IndexingFiltersChecker
- redirects are followed with command-line option -followRedirects
- adds option -normalize to ParserChecker (fixes NUTCH-2145/NUTCH-2554)

NUTCH-2012 Merge parsechecker and indexchecker

---

src/java/org/apache/nutch/fetcher/Fetcher.java
src/java/org/apache/nutch/fetcher/FetcherOutputFormat.java
src/java/org/apache/nutch/fetcher/FetcherThread.java
src/java/org/apache/nutch/fetcher/QueueFeeder.java
src/test/org/apache/nutch/crawl/CrawlDBTestUtil.java

- fix bug in fetcher.QueueFeeder which caused the same key-value pair to be overwritten again and again (Hadoop object reuse)
- simplify URL handling in FetcherThread: hold URLs exclusively in FetchItem
- parametrize log messages and remove unused imports and variables

NUTCH-2553 Fetcher not to modify URLs to be fetched

---

src/java/org/apache/nutch/util/NutchJob.java

As suggested by @HansBrende 
- Added LOG.error in NutchJob.cleanupAfterFailure() sub-routine.

NUTCH-2568 Adding error log in NutchJob.cleanupAfterFailure()

---

conf/regex-urlfilter.txt.template

- provide rules for urlfilter-regex to exclude localhost, loop-back and private IP addresses
- additional rules are not active by default to allow test crawls of content hosted locally

NUTCH-2527 URL filter: provide rules to exclude localhost and private address spaces

---

src/java/org/apache/nutch/fetcher/FetcherOutputFormat.java
src/java/org/apache/nutch/util/SitemapProcessor.java

- use CrawlDb path to get filesystem
- fix Fetcher and SitemapProcessor

NUTCH-2544 Nutch 1.15 no longer compatible with AWS EMR and S3

---

src/java/org/apache/nutch/scoring/ScoringFilter.java
src/plugin/scoring-link/src/java/org/apache/nutch/scoring/link/LinkAnalysisScoringFilter.java
src/plugin/scoring-opic/src/java/org/apache/nutch/scoring/opic/OPICScoringFilter.java

- fix scoring-opic and scoring-link
- check whether CrawlDb datum is null before reading its score
(after NUTCH-2456 which allows to index pages/URLs not contained in CrawlDb)
- complete Java doc

NUTCH-2526 NPE in scoring-opic when indexing document without CrawlDb datum

---

src/java/org/apache/nutch/crawl/DeduplicationJob.java

- run merge job to update status of duplicates to CrawlDb
- lock CrawlDb while running merge job
- cleanup if merge job fails

NUTCH-2570 Deduplication job fails to install deduplicated CrawlDb

---

src/java/org/apache/nutch/segment/SegmentReader.java

simple fix relying on the "old" o.a.hadoop.mapred.SegmentFileOutputFormat.getReaders(...)

NUTCH-2590 SegmentReader -get fails

---

src/java/org/apache/nutch/fetcher/FetcherReducer.java

Without adding on System.currentTimeMillis() this can't possibly work?
According to nutch-default.xml the default value should be 5 minutes.

fix fetcher.throughput.threshold.check.after

---

conf/index-writers.xml.template

commit.mode parameter is used instead of commit.commit in the RabbitMQ indexer.

Fixes for NUTCH-2593 contributed by r0ann3l

---

src/java/org/apache/nutch/crawl/Generator.java

fix the problem of nutch does not delete the .locked file when the generator partition got an exception.

fix for NUTCH-2505 contributed by lianyuzhe

---

conf/nutch-default.xml

- rename property in nutch-default.xml and move to linkdb.* section
In LinkDb.java the property has already been renamed to "linkdb.max.anchor.length".

NUTCH-2530 Rename property db.max.anchor.length > linkdb.max.anchor.length

---

src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpRobotRulesParser.java

- only cache redirected robots.txt rules if the target URL path and query equal /robots.txt

NUTCH-2581 Caching of redirected robots.txt may overwrite correct robots.txt rules

---

src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpRobotRulesParser.java

- only cache redirected robots.txt rules if the target URL path and
query equal /robots.txt

NUTCH-2581 Caching of redirected robots.txt may overwrite correct robots.txt rules (fix for 2.x)

---

build.xml
conf/nutch-default.xml
src/java/org/apache/nutch/metadata/HttpHeaders.java
src/java/org/apache/nutch/net/protocols/Response.java
src/plugin/build.xml
src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpBase.java
src/plugin/protocol-htmlunit/src/java/org/apache/nutch/protocol/htmlunit/HttpResponse.java
src/plugin/protocol-http/src/java/org/apache/nutch/protocol/http/HttpResponse.java
src/plugin/protocol-okhttp/build.xml
src/plugin/protocol-okhttp/ivy.xml
src/plugin/protocol-okhttp/jsp/basic-http.jsp
src/plugin/protocol-okhttp/jsp/brokenpage.jsp
src/plugin/protocol-okhttp/jsp/redirect301.jsp
src/plugin/protocol-okhttp/jsp/redirect302.jsp
src/plugin/protocol-okhttp/plugin.xml
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttp.java
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttpResponse.java
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/package-info.java
src/plugin/protocol-okhttp/src/test/conf/nutch-site-test.xml
src/plugin/protocol-okhttp/src/test/org/apache/nutch/protocol/okhttp/TestBadServerResponses.java
src/plugin/protocol-okhttp/src/test/org/apache/nutch/protocol/okhttp/TestProtocolOkHttp.java

A Nutch protocol plugin based on [okhttp](http://square.github.io/okhttp/):
- derived from @jnioche's implementation for [storm-crawler#443](/DigitalPebble/storm-crawler/issues/443)
- use okhttp's internal buffer for buffering content
- adapted to be compatible to Nutch and behave almost the same as protocol-http
- moved shared configuration settings to HttpBase (lib-http)
- unit tests taken from protocol-http
TODOs:
- verify that issues reported in NUTCH-2549 do not appear again
- complete unit tests
- benchmark and large-scale test
For HTTP/2 support a Java version at runtime is needed which supports ALPN:
```
export NUTCH_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
bin/nutch parsechecker \
-Dplugin.includes='protocol-okhttp|parse-html' \
-Dhttp.useHttp2=true \ …
```

NUTCH-2576 HTTP protocol implementation based on okhttp

---

src/java/org/apache/nutch/protocol/Content.java
src/java/org/apache/nutch/util/MimeUtil.java
src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpBase.java

- avoid creation of new Tika object in constructor of MimeUtil (cache in ObjectCache) - suggested by @YossiTamari. Thanks!
- also hold MimeUtil object in protocol implementation (protocol plugin) and pass it to constructor of Content. This avoids any locks (also those by ObjectCache) in a highly concurrent fetcher. Note that the current MimeUtil implementation and the Tika detector are thread-safe.

NUTCH-2578 Avoid lock by MimeUtil in constructor of protocol.Content

---

src/java/org/apache/nutch/crawl/Generator.java
src/test/org/apache/nutch/crawl/TestGenerator.java

- ensure that also last created segment contains maxCount URLs per host
- use local variable to hold host-specific maxCount set in HostDb  (do not modify instance variable temporarily)
- fix Java compile warnings: add missing generic type parameters

NUTCH-2574 Generator: hostCount >= maxCount comparison wrong

---

conf/index-writers.xml.template
src/java/org/apache/nutch/indexer/IndexingJob.java
src/plugin/indexer-solr/ivy.xml
src/plugin/indexer-solr/plugin.xml
src/plugin/indexer-solr/src/java/org/apache/nutch/indexwriter/solr/SolrConstants.java
src/plugin/indexer-solr/src/java/org/apache/nutch/indexwriter/solr/SolrIndexWriter.java
src/plugin/indexer-solr/src/java/org/apache/nutch/indexwriter/solr/SolrUtils.java

This patch includes an update for solrj library from version 5.5.0 to 7.3.1. According to [SOLR-8903](https://issues.apache.org/jira/browse/SOLR-8903), the lastest available version of this library doesn't include `DateUtil` class, so for formatting the dates I used `DateTimeFormatter.ISO_INSTANT.format(d.toInstant())` instead. In addition, the weight of a document is no longer supported by this library as an attribute of `SolrInputDocument` class and for that reason I include a new paramater: "weight.field", indicating the field's name where the document weight should be written. Also, Basic Authentication is now supported.
On the other side, I refactored the code, deleting some unused constants, unsed parameters and including others in index-writers.xml.
This PR was tested in Solr 6.3.0 …

fix for NUTCH-2600: indexer-solr refactoring

---

conf/index-writers.xml.template

CloudSearch implementation class fixed on index-writers.xml.template

fix for NUTCH-2601: CloudSearch implementation class.

---

src/plugin/urlnormalizer-basic/src/java/org/apache/nutch/net/urlnormalizer/basic/BasicURLNormalizer.java
src/plugin/urlnormalizer-basic/src/test/org/apache/nutch/net/urlnormalizer/basic/TestBasicURLNormalizer.java

Fixes for
- NUTCH-2547 urlnormalizer-basic fails on special characters in path/query
- NUTCH-2609 urlnormalizer-basic to normalize path of file: URLs
In detail:
- escape more special characters
- escape percent when not followed by a valid escape sequence
(two-digit hex number)
- escape special characters before normalizing the path
so that URI.normalize() can be used on valid URIs
- also normalize path '/..'
- normalize path on file: URLs
- complete unit tests

NUTCH-2547 NUTCH-2609 urlnormalizer-basic

---

src/java/org/apache/nutch/crawl/CrawlDbReader.java

Trivial fix: assume zero if no "total count" element is in statistics map

NUTCH-2614 NPE in CrawlDbReader -stats on empty CrawlDb

---

conf/nutch-default.xml
conf/regex-urlfilter.txt.template
src/java/org/apache/nutch/fetcher/FetcherThread.java
src/java/org/apache/nutch/parse/ParseOutputFormat.java

- add property db.max.outlink.length to limit length of outlinks and redirects (default = 8192 characters)
- check length in ParseOutputFormat and FetcherThread for outlinks and redirects
- also add rule (not active, commented out) to regex-urlfilters.txt.template

NUTCH-1106 Options to skip url's based on length

---

conf/nutch-default.xml
src/java/org/apache/nutch/net/protocols/Response.java
src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpBase.java
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttpResponse.java

If http.partial.truncated is true and there is already content fetched, the content is returned as successful response but marked as truncated. Tested by disconnecting network while fetching an overlong documents (10 MB).
PR includes and is based on fix for NUTCH-2618.

NUTCH-2619 protocol-okhttp: allow to keep partially fetched docs as truncated

---

src/java/org/apache/nutch/parse/ParseResult.java
src/java/org/apache/nutch/parse/ParseUtil.java

- apply patch contributed by Arkadi Kosmynin
- return last failed parse result (the empty result returned otherwise does not contain the failure reason)
- improve javadoc

NUTCH-1993 Nutch does not use backup parsers

---

ivy/ivy.xml

- exclude LGPL-licensed dsiutils and libidn as dependencies of webarchive-commons
- provide instructions how to include the excluded libs when building from source to make `nutch commoncrawldump -warc ...` work
- fix/unify whitespace in ivy file

NUTCH-2622 Unbundle LGPL-licensed jars from binary release

---

src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttp.java

This adds proxy authentication to the protocol-okhttp plugin.
Note that whenever proxy authentication is enabled with protocol-okhttp (i.e. whenever http.proxy.username is present), Nutch's http.proxy.exclusion.list feature will be disabled. There is a bug filed on the okhttp GitHub repo (https://github.com/square/okhttp/issues/3995) that is blocking these features from working together.

NUTCH-2632 protocol-okhttp proxy authentication

---

build.xml
ivy/ivy-report-license.xsl
src/plugin/build-plugin.xml

- add ant target `ant report-licenses` (for core and plugins) which generates tabular reports of dependency licenses
The created table is comparable to those created by the [Maven license plugin](https://www.mojohaus.org/license-maven-plugin/index.html)
- it also shows dual licenses (important if one of the alternatives is compatible with the Apache license)
- must be called separately for core and each plugin, e.g.
```
ant report-licenses
more build/org.apache.nutch-nutch-default-3rd-party-licenses.tsv
cd src/plugin/any23
ant report-licenses
more ../../../build/any23/org.apache.nutch-any23-default-3rd-party-licenses.tsv
```

NUTCH-2621 Generate report of third-party licenses

---

src/java/org/apache/nutch/fetcher/FetcherJob.java

I'm kind a new to this, so sorry if i'm wrong.
The thing is the number of fetcher reducers are currently set to the value of "mapreduce.job.maps" when the arg not passed. It should be "mapreduce.job.reduces".
JIRA URL: https://issues.apache.org/jira/browse/NUTCH-2637
thanks

NUTCH-2637 fix number of reducers to run

---

src/plugin/index-more/src/java/org/apache/nutch/indexer/more/MoreIndexingFilter.java
src/plugin/index-more/src/test/org/apache/nutch/indexer/more/TestMoreIndexingFilter.java

- fix date pattern not to convert date in local time zone
(as suggested by John Lacey)
- do not add last-modified date if there is none
- add unit test

NUTCH-2642 MoreIndexingFilter parses ISO 8601 UTC dates in local time zone

---

src/java/org/apache/nutch/crawl/Generator.java

- output is written to MultipleOutputs, skip context.write(...)
- fix comment wrapping

NUTCH-2635 Generator writes unneeded temporary output

---

conf/nutch-default.xml
src/java/org/apache/nutch/fetcher/FetchItem.java
src/java/org/apache/nutch/fetcher/FetchItemQueues.java
src/java/org/apache/nutch/fetcher/FetcherThread.java

- the modes byHost, byDomain and byIP now do not include the protocol for assigning URLs to queues
- added fetcher.queue.mode `byHostProtocol` for legacy
- centralize check of queue mode

NUTCH-2623 Fetcher to guarantee delay for same host/domain/ip independent of http/https protocol

---

conf/nutch-default.xml
src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpBase.java
src/plugin/protocol-http/src/java/org/apache/nutch/protocol/http/HttpResponse.java
src/plugin/protocol-httpclient/src/java/org/apache/nutch/protocol/httpclient/Http.java
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttp.java

- enable/disable validation of certs by property `http.tls.certificates.check` (default: false/disabled)
- add support to skip certificate validation in protocol-okhttp

 NUTCH-2648 Make configurable whether TLS/SSL certificates are checked by protocol plugins

---

LICENSE.txt
conf/parse-plugins.xml
conf/regex-normalize.xml.template
ivy/ivy.xml
src/java/org/apache/nutch/parse/OutlinkExtractor.java
src/plugin/parse-js/build.xml
src/plugin/parse-js/plugin.xml
src/plugin/parse-js/sample/parse_embedded_js_test.html
src/plugin/parse-js/sample/parse_pure_js_test.js
src/plugin/parse-js/src/java/org/apache/nutch/parse/js/JSParseFilter.java
src/plugin/parse-js/src/test/org/apache/nutch/parse/js/TestJSParseFilter.java
src/plugin/urlnormalizer-regex/sample/regex-normalize-default.xml
src/plugin/urlnormalizer-regex/sample/regex-normalize-scope1.xml

(also fixes NUTCH-1678, NUTCH-1014 and NUTCH-1021)
- apply Markus' patch of NUTCH-2192
- finish migration of parse-js
- remove oro dependency
- correct pointer to Java regex syntax (instead of "Perl5")
- NUTCH-1063 "OutlinkExtractor test generates an exception but does not fail" is fixed by adding null-check (required anyway by java.util.regex classes)
- adds a JUnit test for parse-js (NUTCH-1121) ported from 2.x and extended

NUTCH-2192 Migrate from Apache ORO to java.util.regex

---

LICENSE.txt
conf/parse-plugins.xml
conf/regex-normalize.xml.template
ivy/ivy.xml
src/java/org/apache/nutch/parse/OutlinkExtractor.java
src/plugin/index-more/src/java/org/apache/nutch/indexer/more/MoreIndexingFilter.java
src/plugin/parse-js/plugin.xml
src/plugin/parse-js/sample/parse_pure_js_test.js
src/plugin/parse-js/src/java/org/apache/nutch/parse/js/JSParseFilter.java
src/plugin/parse-js/src/test/org/apache/nutch/parse/js/TestJSParseFilter.java
src/plugin/urlnormalizer-regex/sample/regex-normalize-default.xml
src/plugin/urlnormalizer-regex/sample/regex-normalize-scope1.xml

(cf. NUTCH-2192)
- replace oro with java.util.regex classes in OutlinkExtractor, plugins parse-js and index-more
- extend unit tests of parse-js
- correct pointer to Java regex syntax (instead of "Perl5")

NUTCH-1678 Remove dependency on org.apache.oro

---

build.xml
default.properties
src/plugin/build.xml
src/plugin/headings/build.xml

- add missing unit test packages to plugin build.xml
- tests of "headings" plugin depend on "lib-nekohtml"
- add "protocol-okhttp" to Javadoc API overview
- add missing test packages to ant "eclipse" target

NUTCH-2660 Plugin tests not executed

---

src/java/org/apache/nutch/fetcher/Fetcher.java

- properly override method [getSplits(JobContext context) of FileInputFormat](https://hadoop.apache.org/docs/r2.8.5/api/org/apache/hadoop/mapreduce/lib/input/FileInputFormat.html#getSplits(org.apache.hadoop.mapreduce.JobContext))

NUTCH-2652 Fetcher launches more fetch tasks than fetch lists

---

conf/schema.xml

As discussed in #398 it makes perfect sense to add the fields required by the index-links plugin to the `conf/schema.xml`.

Add the fields required by the index-links plugin to the Solr schema

---

src/java/org/apache/nutch/fetcher/FetcherThread.java

Change required log level to INFO (default) for messages reporting skipped URLs because of robots.txt rules (disallow or crawl delay larger than fetcher.max.crawl.delay).

NUTCH-2630 Fetcher to log skipped records by robots.txt

---

src/java/org/apache/nutch/crawl/Generator.java

The documentation in nutch-default.xml says this value is in milliseconds, but the code assumes it is in days.

NUTCH-1842: crawl.gen.delay value is read incorrectly from config

---

src/java/org/apache/nutch/util/MimeUtil.java
src/test/org/apache/nutch/util/TestMimeUtil.java

- allow text/plain (from MIME magic) to overwrite type derived from HTTP Content-Type or file extension

NUTCH-2606 MIME detection is wrong for plain-text documents send as Content-Type "application/msword"

---

build.xml
ivy/dependency-check-ant/dependency-check-suppressions.xml

[OWASP](http://www.owasp.org/) provides an ant tool "[dependency-check](https://jeremylong.github.io/DependencyCheck/dependency-check-ant/index.html)" which lists potential vulnerabilities of library dependencies.
To install the tool (eventually the installation can be automatized as ant target):
```
wget http://dl.bintray.com/jeremy-long/owasp/dependency-check-ant-3.3.2-release.zip
unzip -d ivy/ dependency-check-ant-3.3.2-release.zip
```
Run it
```
ant report-vulnerabilities
```
and open the reports `build/dependency-check-report.html` or `build/dependency-check-vulnerability.html`. There are false positives, the tool allows to maintain an suppression list which needs to be completed.

NUTCH-2668 Integrate OWASP dependency checks as ant target

---

src/java/org/apache/nutch/hostdb/ReadHostDb.java

- replace column headers `redirSum \t ok` with `notModified` to match actual dump of HostDb

NUTCH-2674 HostDb: dump shows wrong column headers

---

src/plugin/index-links/README.md

Add a README file for the index-links plugin. At the very least, least this solves part of the issue with users knowing what they need to add to their backend (usually Solr).

NUTCH-2658 Add README for the index-links plugin

---

src/plugin/protocol-http/src/java/org/apache/nutch/protocol/http/HttpResponse.java

- store response headers using "\r\n" and two trailing line breaks at the end of the headers

NUTCH-2657 Protocol-http to store HTTP response header with "\r\n"

---

conf/nutch-default.xml
src/java/org/apache/nutch/fetcher/FetcherThread.java

- add property fetcher.signature to make fetcher generate a signature even if fetcher is not parsing
- move comment about following meta-redirects for multi-parse ParseResults into the right position

NUTCH-2628 Fetcher: optionally generate signature of unparsed content

---

conf/nutch-default.xml
src/plugin/index-more/src/java/org/apache/nutch/indexer/more/MoreIndexingFilter.java

Includes a new property: "moreIndexingFilter.mapMimeTypes.field", which indicates the field's name where the mapped mime type must be written. If this property is NULL (default value) the field "type" will be replaced by the mapped mime type (current behavior).

NUTCH-2686 New property: "moreIndexingFilter.mapMimeTypes.field"

---

conf/regex-urlfilter.txt.template
src/plugin/lib-regex-filter/src/java/org/apache/nutch/urlfilter/api/RegexURLFilterBase.java
src/plugin/urlfilter-regex/sample/Benchmarks.rules
src/plugin/urlfilter-regex/sample/IntranetCrawling.rules
src/plugin/urlfilter-regex/sample/WholeWebCrawling.rules

- do not extract host and domain name from the URL if not needed
- speed up regular expressions:
- use non-capturing groups if possible
- use (?i) to make the patterns case insensitive and remove uppercase variants to keep alternations shorter

NUTCH-2689 Speed up urlfilter-regex and urlfilter-automaton

---

conf/nutch-default.xml
src/java/org/apache/nutch/crawl/Generator.java
src/java/org/apache/nutch/net/protocols/Response.java
src/plugin/indexer-csv/src/java/org/apache/nutch/indexwriter/csv/CSVIndexWriter.java
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttp.java
src/plugin/scoring-orphan/src/test/org/apache/nutch/scoring/orphan/TestOrphanScoringFilter.java
src/test/org/apache/nutch/crawl/TestGenerator.java

- fix wrong names of Nutch configuration properties in documentation (nutch-default.xml and Java comments)
- also fix further typos

NUTCH-2693 Misspelled configuration property names in documentation

---

default.properties
ivy/ivysettings.xml

Reverts apache/nutch#441 because using ivy-2.5.0-rc1 causes [NUTCH-2672](https://issues.apache.org/jira/browse/NUTCH-2672).

Revert "NUTCH-2697: Upgrade Ivy to fix the issue of an unset packaging.type p…"

---

conf/nutch-default.xml
src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpBase.java
src/plugin/protocol-file/src/java/org/apache/nutch/protocol/file/File.java
src/plugin/protocol-ftp/src/java/org/apache/nutch/protocol/ftp/Ftp.java

Increase the default content limit from 64 kB to 1024 kB for http, ftp and file protocol plugins.

NUTCH-2666 Increase default value for http.content.limit / ftp.content.limit / file.content.limit

---

src/java/org/apache/nutch/fetcher/Fetcher.java
src/java/org/apache/nutch/util/TimingUtil.java

- add human-readable date to log message about time limit
- move date formatter to TimingUtil
- use new thread-safe date and time API

NUTCH-2701 Fetcher: log dates and times also in human-readable form

---

src/java/org/apache/nutch/indexer/IndexingFiltersChecker.java
src/java/org/apache/nutch/parse/ParserChecker.java

... and add options `-doIndex` to pass "checked" document to index writers (the property `doIndex` is kept to ensure back-ward compatibility):
```
% bin/nutch indexchecker
Usage:
IndexingFiltersChecker [OPTIONS] <url>
Fetch single URL and index it
IndexingFiltersChecker [OPTIONS] -stdin
Read URLs to be indexed from stdin
IndexingFiltersChecker [OPTIONS] -listen <port> [-keepClientCnxOpen]
Listen on <port> for URLs to be indexed
Options:
-D<property>=<value>  set/overwrite Nutch/Hadoop properties
(a generic Hadoop option to be passed
before other command-specific options)
-normalize            normalize URLs
-followRedirects      follow redirects when fetching URL
-dumpText             show the entire plain-text content,
not only the first 100 characters
-doIndex              pass document …
```

NUTCH-2700 Indexchecker: improve command-line help

---

src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttpResponse.java

Significantly less loops are now executed:
```
2019-03-13 17:46:25,232 DEBUG okhttp.OkHttpResponse - http://localhost/large.pdf - http/1.1 200 OK
2019-03-13 17:46:25,233 DEBUG okhttp.OkHttpResponse - total bytes requested = 8192, buffered = 16088
2019-03-13 17:46:25,233 DEBUG okhttp.OkHttpResponse - total bytes requested = 24280, buffered = 24280
2019-03-13 17:46:25,233 DEBUG okhttp.OkHttpResponse - total bytes requested = 32472, buffered = 32472
2019-03-13 17:46:25,233 DEBUG okhttp.OkHttpResponse - total bytes requested = 40664, buffered = 40664
2019-03-13 17:46:25,233 DEBUG okhttp.OkHttpResponse - total bytes requested = 48856, buffered = 48856
2019-03-13 17:46:25,233 DEBUG okhttp.OkHttpResponse - total bytes requested = 57048, buffered = 57048
2019-03-13 17:46:25,233 DEBUG …
```

NUTCH-2699 Protocol-okhttp: needless loops to increment requested bytes counter when more content is already buffered

---

src/java/org/apache/nutch/util/PrefixStringMatcher.java
src/java/org/apache/nutch/util/TrieStringMatcher.java

- move code preparing TrieNode for matching into synchronized method
- javadoc: add note about thread-safety
- add test for thread-safety to main() method of PrefixStringMatcher using parallel streams calling the match method

NUTCH-2585 trie string matcher

---

conf/nutch-default.xml
src/java/org/apache/nutch/protocol/ProtocolStatus.java
src/plugin/creativecommons/conf/nutch-site.xml
src/plugin/protocol-http/src/java/org/apache/nutch/protocol/http/Http.java

- remove `http.verbose` and related code (commented out)
- remove `http.max.delays` which is obsolete since handling of politeness and delays is handled in the multi-threaded Fetcher (see NUTCH-339 and NUTCH-876)

NUTCH-2709 Remove unused properties and code related to HTTP protocol

---

build.xml
ivy/ivysettings.xml
ivy/mvn.template

PR for 1.x (needs similarly applied to 2.x and 2.4)
- change the Maven repository URL to https
- remove mirrors (mostly outdated anyway)
- work-around to avoid that the `ant restdoc` task fetches from `http://repo1.maven.org/` (the URL seems to be hardwired in the [Maven ant task project/library](https://maven.apache.org/ant-tasks/) (not maintained anymore)

NUTCH-2722 Fetch dependencies via https

---

conf/nutch-default.xml
src/java/org/apache/nutch/fetcher/FetcherThread.java
src/java/org/apache/nutch/net/protocols/ProtocolLogUtil.java
src/java/org/apache/nutch/net/protocols/package-info.java
src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpBase.java

- exceptions listed in `http.log.exceptions.suppress.stack` are logged without stack trace
- exclusions are checked when errors are logged in FetcherThread and HttpBase.getResponse(...)

NUTCH-2702 Fetcher: suppress stack for frequent exceptions

---

src/plugin/indexer-solr/src/java/org/apache/nutch/indexwriter/solr/SolrIndexWriter.java

Thanks for your attention - I have submitted the fix and created the relevant ticket in JIRA. The fix is fairly straightforward, following the same pattern used for commits and writes.

NUTCH-2731 Fix to ensure that credentials are set on delete operations.

---

ivy/ivy.xml
src/java/org/apache/nutch/protocol/ProtocolFactory.java
src/plugin/protocol-okhttp/src/test/conf/nutch-site-test.xml
src/plugin/protocol-okhttp/src/test/org/apache/nutch/protocol/okhttp/TestBadServerResponses.java
src/plugin/protocol-okhttp/src/test/org/apache/nutch/protocol/okhttp/TestProtocolOkHttp.java

- fix unit tests of protocol-okhttp to use plugin class loader
and methods defined by Protocol interface to avoid dependency
conflicts (Hadoop depends on okhttp as well)

NUTCH-2727 Upgrade Hadoop dependencies to 2.9.2

---

conf/nutch-default.xml
src/java/org/apache/nutch/exchange/Exchanges.java
src/java/org/apache/nutch/indexer/IndexWriters.java

With this patch, select another file for exchanges and index writers configuration is available out-of-the-box. For this purpose there are two new properties: `exchanges.exchanges.file` and `indexer.indexwriters.file`

NUTCH-2718: Filenames of configuration files of index writers and exchanges

---

src/java/org/apache/nutch/indexer/IndexWriters.java

When an exchange points to a non-existent index writer, Nutch logs a warning indicating the inconsistent configuration and avoids the current NPE.

NUTCH-2719: An exchange points to an index writer not available

---

ivy/ivy.xml
ivy/ivysettings.xml
src/plugin/parse-tika/build-ivy.xml

- update org.apache.cxf to drop javax.ws.rs-api dependency

NUTCH-2669 Reliable solution for javax.ws packaging.type

---

src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttpResponse.java
src/plugin/protocol-okhttp/src/test/org/apache/nutch/protocol/okhttp/TestBadServerResponses.java

- request one byte more than the configured content limit (http.content.limit) to detect truncations reliably
- add unit tests for marking of truncations, also for gzip Content-Encoding and chunked Transfer-Encoding

NUTCH-2729 protocol-okhttp: fix marking of truncated content

---

src/java/org/apache/nutch/net/URLNormalizerChecker.java

Output empty string for invalid URLs and do not exit.

NUTCH-2598 URLNormalizerChecker fails on invalid URLs in input

---

docker/Dockerfile
docker/README.md

- upgrade to use Ubuntu 18.04
- remove installed packages not required to build Nutch

NUTCH-2736 Upgrade Dockerfile to be based on recent Ubuntu LTS version

---

conf/nutch-default.xml
src/java/org/apache/nutch/crawl/CrawlDatum.java
src/java/org/apache/nutch/crawl/Generator.java

Generator improvements to address NUTCH-2737 and NUTCH-2738:
- add counters for skipped URLs in Selector mapper and reducer
- document generate.restrict.status
- parameterize log messages

NUTCH-2737 NUTCH-2738 Generator: count and log reason of rejections during selection, document property generate.restrict.status

---

conf/nutch-default.xml
src/java/org/apache/nutch/util/SitemapProcessor.java

Override http.content.limit with sitemap.size.max when fetching sitemaps. Defaults to 50MB.

Nutch-2511 Support large sitemaps

---

src/plugin/parse-metatags/src/java/org/apache/nutch/parse/metatags/MetaTagsParser.java
src/plugin/parse-metatags/src/test/org/apache/nutch/parse/metatags/TestMetatagParser.java

- do not add metatags already in ParseData's as this may lead to duplicates
- add unit test
- fix logging in MetaTagsParser to use slf4j

NUTCH-1559 parse-metatags duplicates extracted metatags

---

conf/nutch-default.xml
src/plugin/urlnormalizer-basic/src/java/org/apache/nutch/net/urlnormalizer/basic/BasicURLNormalizer.java
src/plugin/urlnormalizer-basic/src/java/org/apache/nutch/net/urlnormalizer/basic/package-info.java
src/plugin/urlnormalizer-basic/src/test/org/apache/nutch/net/urlnormalizer/basic/TestBasicURLNormalizer.java

- convert domain names IDN to ASCII or ASCII to IDN (configured by urlnormalizer.basic.host.idn)
- strip trailing dot in host names (if urlnormalizer.basic.host.trim-trailing-dot is true)

NUTCH-2746 Basic URL normalizer to normalize Unicode domain names

---

conf/nutch-default.xml
src/java/org/apache/nutch/fetcher/FetcherThread.java

(final solution, commits need to be squashed before merging)
- new configuration property `http.redirect.max.exceeded.skip`:
- if true skip redirect targets if http.redirect.max is exceeded
- if false (default): store the redirect targets with status "linked"
- log whether exceeded redirects are "skipped" or "linked":
```
FetcherThread 44 - redirect count exceeded https://en.wikipedia.org/wiki/URL_redirection (skipped)
```
resp.
```
FetcherThread 44 - redirect count exceeded https://en.wikipedia.org/wiki/URL_redirection (linked)
```

NUTCH-2748 Fetch status gone (redirect exceeded) not to overwrite existing items in CrawlDb

---

src/java/org/apache/nutch/protocol/RobotRulesParser.java

Initialize crawler-commons's SimpleRobotRulesParser with the longest possible internal maxDelay so that Nutch can always handle the max. delay by itself.

NUTCH-2754 fetcher.max.crawl.delay ignored if exceeding 5 min. / 300 sec.

---

src/java/org/apache/nutch/indexer/IndexerMapReduce.java
src/java/org/apache/nutch/indexer/IndexingJob.java

This PR obsoletes #95 (parts of the work are already done in [NUTCH-2456](https://issues.apache.org/jira/browse/NUTCH-2456)/#240). It
- makes the CrawlDb argument passed to indexing job optional
- but does not change the behavior of the indexing job otherwise
- if there are non-optional arguments, the first of them is expected to be the CrawlDb unless `-nocrawldb` is given
- it picks various improvements from PR #95
- and improves the command-line help:
```
Usage: Indexer (<crawldb> | -nocrawldb) (<segment> ... | -dir <segments>) [general options]
Index given segments using configured indexer plugins
The CrawlDb is optional but it is required to send deletion requests for duplicates
and to read the proper document score/boost/weight passed to the indexers.
Required arguments:
<crawldb> …
```

NUTCH-2184 Enable IndexingJob to function with no crawldb

---

src/plugin/index-metadata/src/java/org/apache/nutch/indexer/metadata/MetadataIndexer.java

- apply patch contributed by Jurian Broertjes to recent master

NUTCH-2525 Metadata indexer cannot handle uppercase parse metadata

---

src/bin/crawl

Renamed option --num-slaves to --num-fetchers:
```
--num-fetchers <num_fetchers>        Number of tasks used for fetching (fetcher map tasks) [default: 1]
Note: This can only be set when running in distributed mode and
should correspond to the number of worker nodes in the cluster.
```

NUTCH-2759 bin/crawl: Rename option --num-slaves

---

src/plugin/protocol-okhttp/ivy.xml
src/plugin/protocol-okhttp/plugin.xml
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttp.java

- upgrade to okhttp 4.3.2
- add dependency to okhttp3.brotli and enable Brotli compression
```
$> bin/nutch parsechecker -Dstore.http.headers=true -Dstore.http.request=true \
-Dplugin.includes='protocol-okhttp|parse-html'  https://www.youtube.com/
...
_request_=GET / HTTP/1.1
...
Accept-Encoding: br,gzip
...
_response.headers_=HTTP/1.1 200 OK
Content-Encoding: br
...
```
I'll run a test crawl with some additional metrics soon.

NUTCH-2733 protocol-okhttp: add support for Brotli compression (Content-Encoding)

---

src/java/org/apache/nutch/fetcher/FetchItemQueue.java
src/java/org/apache/nutch/fetcher/FetchItemQueues.java
src/java/org/apache/nutch/fetcher/Fetcher.java
src/java/org/apache/nutch/fetcher/QueueFeeder.java

- each queue checks whether max. exceptions are reached when adding a new fetch item - if yes, the item is not added to the queue
- for proper counting and logging the queuing status is reported to QueueFeeder

NUTCH-2767 Fetcher to stop filling queues skipped due to repeated exception

---

src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttp.java
src/plugin/protocol-okhttp/src/test/org/apache/nutch/protocol/okhttp/TestBadServerResponses.java

(see [NUTCH-2763](https://issues.apache.org/jira/browse/NUTCH-2763))

NUTCH-2763 protocol-okhttp (store.http.headers): add whitespace in status line after status code also when message is empty

---

conf/nutch-default.xml
src/java/org/apache/nutch/protocol/Content.java
src/java/org/apache/nutch/segment/SegmentReader.java

- if called with command-line flag `-recode` (or if property `segment.reader.content.recode` is true): try to recode the HTML page content to UTF-8 using the already detected charset
- fix passing forward properties (-Dprop=val) to Hadoop job/tasks
* always use same Hadoop Configuration
* use single instance of SegmentReader for -get and -list
* remove duplicating member and local variables

NUTCH-2773 SegmentReader (-dump or -get): show HTML content as UTF-8

---

conf/nutch-default.xml
src/java/org/apache/nutch/fetcher/FetcherThread.java

The guaranteed minimum delay is configured by `fetcher.min.crawl.delay`, default is set equal to `fetcher.server.delay`.

NUTCH-2775 Fetcher to guarantee minimum delay even if robots.txt defines shorter Crawl-delay

---

conf/index-writers.xml.template
src/plugin/indexer-elastic/README.md
src/plugin/indexer-elastic/src/java/org/apache/nutch/indexwriter/elastic/ElasticConstants.java
src/plugin/indexer-elastic/src/java/org/apache/nutch/indexwriter/elastic/ElasticIndexWriter.java

Added username and password as default credentials to the HTTP Client

NUTCH-2757 : Indexer-elastic: add authentication options

---

src/java/org/apache/nutch/crawl/CrawlDb.java
src/java/org/apache/nutch/crawl/CrawlDbMerger.java
src/java/org/apache/nutch/crawl/CrawlDbReader.java
src/java/org/apache/nutch/crawl/CrawlDbReducer.java
src/java/org/apache/nutch/crawl/DeduplicationJob.java
src/java/org/apache/nutch/crawl/Generator.java
src/java/org/apache/nutch/crawl/Injector.java
src/java/org/apache/nutch/crawl/LinkDb.java
src/java/org/apache/nutch/crawl/LinkDbReader.java
src/java/org/apache/nutch/crawl/SignatureFactory.java
src/java/org/apache/nutch/fetcher/Fetcher.java
src/java/org/apache/nutch/fetcher/FetcherThread.java
src/java/org/apache/nutch/hostdb/UpdateHostDbMapper.java
src/java/org/apache/nutch/hostdb/UpdateHostDbReducer.java
src/java/org/apache/nutch/indexer/IndexerMapReduce.java
src/java/org/apache/nutch/parse/ParseSegment.java
src/java/org/apache/nutch/parse/ParserChecker.java
src/java/org/apache/nutch/segment/SegmentMerger.java
src/java/org/apache/nutch/tools/FreeGenerator.java
src/java/org/apache/nutch/util/SitemapProcessor.java
src/plugin/indexer-solr/src/java/org/apache/nutch/indexwriter/solr/SolrIndexWriter.java

- replace logging messages with string concatenations by parametrized calls
- remove `LOG.isInfoEnabled()`  where parametrized logging is used and no or minor extra calls are one to get logging parameters (similar for other log levels)
- replace needless `.toString()` and `Integer.toString(intVal)`

NUTCH-2783 Use (more) parametrized logging

---

src/bin/crawl
src/bin/nutch

- increase default value for NUTCH_HEAPSIZE to 4096 MB (from 1000 MB)
- remove -Dmapred.child.java.opts=-Xmx1000m from default options in bin/crawl

NUTCH-2781 Increase default Java heap size

---

src/bin/crawl
src/bin/nutch

- bin/crawl
- add hint how to set map and reduce task memory via -D ... options
- use -D options for all steps (Nutch tools), fixes [NUTCH-2379](https://issues.apache.org/jira/projects/NUTCH/issues/NUTCH-2379)
- fix quoting of -D options, eg. -D plugin.includes='protocol-xyz|parse-xyz'
- use -D options for all steps (Nutch tools)
- bin/nutch
- document that environment variables are only used in local mode
(includes #512 / NUTCH-2781)

NUTCH-2501 allow to set Java heap size when using crawl script in distributed mode

---

src/plugin/indexer-elastic/src/java/org/apache/nutch/indexwriter/elastic/ElasticIndexWriter.java

- add log output in BulkProcessor.Listener
- do not throw an exception in BulkProcessor.Listener which is ignored anyway (but this might need a closer look)

NUTCH-2778 indexer-elastic to properly log errors

---

conf/nutch-default.xml
src/java/org/apache/nutch/fetcher/FetchItemQueues.java
src/java/org/apache/nutch/fetcher/FetcherThread.java

- cache followed redirect targets for a configurable time (`fetcher.redirect.dedupcache.seconds`)
- if a redirect target is found in cache it's skipped

NUTCH-2776 Fetcher to temporarily deduplicate followed redirects

---

src/bin/crawl

Note: this PR includes PR #513 to avoid merge conflicts.

NUTCH-2495: Use -deleteGone instead of clean job in crawl script while indexing

---

src/bin/nutch
src/java/org/apache/nutch/tools/ShowProperties.java

Because it's a Nutch/Hadoop tool it really uses the same configuration mechanism as all other tools, including command-line overrides:
```bash
$> bin/nutch showproperties | (head -2 && grep delay)
conf.name                                       conf.value     substituted.value
================================================================================
crawl.gen.delay                                                        604800000
fetcher.max.crawl.delay                                                       30
fetcher.min.crawl.delay              ${fetcher.server.delay}                 5.0
fetcher.server.delay                                                         5.0
fetcher.server.min.delay                                                     0.0
ipc.client.tcpnodelay …
```

NUTCH-2784 Add tool to list Nutch and Hadoop properties

---

src/java/org/apache/nutch/crawl/Generator.java
src/java/org/apache/nutch/util/NutchJob.java

- release CrawlDb lock after select step, in case, generated items are not marked in CrawlDb (generate.update.crawldb is false)

NUTCH-1194 Generator: CrawlDB lock should be released earlier

---

src/plugin/parsefilter-regex/src/java/org/apache/nutch/parsefilter/regex/RegexParseFilter.java
src/plugin/parsefilter-regex/src/test/org/apache/nutch/parsefilter/regex/TestRegexParseFilter.java
src/plugin/urlfilter-domain/src/java/org/apache/nutch/urlfilter/domain/DomainURLFilter.java
src/plugin/urlfilter-domain/src/test/org/apache/nutch/urlfilter/domain/TestDomainURLFilter.java
src/plugin/urlfilter-domainblacklist/src/java/org/apache/nutch/urlfilter/domainblacklist/DomainBlacklistURLFilter.java
src/plugin/urlfilter-domainblacklist/src/test/org/apache/nutch/urlfilter/domainblacklist/TestDomainBlacklistURLFilter.java
src/plugin/urlfilter-prefix/src/java/org/apache/nutch/urlfilter/prefix/PrefixURLFilter.java
src/plugin/urlfilter-suffix/src/java/org/apache/nutch/urlfilter/suffix/SuffixURLFilter.java
src/plugin/urlnormalizer-host/src/java/org/apache/nutch/net/urlnormalizer/host/HostURLNormalizer.java
src/plugin/urlnormalizer-host/src/test/org/apache/nutch/net/urlnormalizer/host/TestHostURLNormalizer.java
src/plugin/urlnormalizer-protocol/src/java/org/apache/nutch/net/urlnormalizer/protocol/ProtocolURLNormalizer.java
src/plugin/urlnormalizer-protocol/src/test/org/apache/nutch/net/urlnormalizer/protocol/TestProtocolURLNormalizer.java
src/plugin/urlnormalizer-slash/src/java/org/apache/nutch/net/urlnormalizer/slash/SlashURLNormalizer.java
src/plugin/urlnormalizer-slash/src/test/org/apache/nutch/net/urlnormalizer/slash/TestSlashURLNormalizer.java

- fix urlfilter-domain, urlfilter-domainblacklist, urlfilter-prefix and urlfilter-suffix
- always prefer the configured rule file (urlfilter.domain.file, urlfilter.domainblacklist.file, urlfilter.prefix.file, urlfilter.suffix.file) over the file defined in plugin.xml
- remove constructors taking rule file as argument (used only in unit tests and now obsolete because we can override the rule file via configuration)
- update Java API doc comments

NUTCH-2419 Some URL filters and normalizers do not respect command-line override for rule file

---

src/bin/crawl

- disable URL filtering and normalizing when calling invertlinks in bin/crawl
- add note that the steps invertlinks, dedup, index could also be done outside the loop over all segments created in the loop iterations
- move webgraph construction (commented out anyway) outside the loop because it's done over all available segments

NUTCH-2496 Speed up link inversion step in crawling script

---

src/java/org/apache/nutch/util/CrawlCompletionStats.java
src/java/org/apache/nutch/util/ProtocolStatusStatistics.java
src/java/org/apache/nutch/util/domain/DomainStatistics.java

- Handle Google Cloud Storage URLs as crawldb inputs in domainstats,
protocolstats and crawlcomplete commands.
- Correctly resolve numReducers in protocolstats.
- Align crawlcomplete -inputDirs behaviour on the other commands: expect
directories containing "current", not "crawldb/current".
Like the other PR, I cannot run all tests locally. But I am not too worried, test-core pass.
Also, these changes are not super high quality in the sense that ideally I would have added some helper to enforce path manipulations which work with URLs, for all commands. Now, I do not think these commands deserve so much work so:
- I just copy/paste "Path" manipulations used in other commands like CrawlDBReader which I know work locally and in GCS. Then run the commands in GCP and some of them again locally …

NUTCH-2791 Handle GCS URLs in stats commands

---

ivy/ivy.xml
src/java/org/apache/nutch/util/SitemapProcessor.java

[NUTCH-2796] Upgrade to crawler-commons 1.1
[NUTCH-2730] SitemapProcessor to treat sitemap URLs as Set instead of List
- sitemap links from robots.txt are treated as set by crawler-commons (since crawler-commons 1.1)
- sitemaps referenced in sitemap index are deduplicated

[NUTCH-2796] [NUTCH-2730] Update crawler-commons 1.1, SitemapProcessor to treat sitemap URLs as Set instead of List

---

src/java/org/apache/nutch/protocol/RobotRulesParser.java

- if no agent names are given as command-line arguments use values ofhttp.agent.name and http.robots.agents as agent names to be checked
- update command-line help
```
$> nutch org.apache.nutch.protocol.RobotRulesParser \
-Dhttp.agent.name='mybot' \
-Dhttp.robots.agents='nutch,goodbot' \
robots.txt urls.txt 
Testing robots.txt for agent names: mybot,nutch,goodbot
allowed:        https://www.example.com/
$> nutch org.apache.nutch.protocol.RobotRulesParser \
-Dhttp.agent.name='mybot' \
-Dhttp.robots.agents='nutch,goodbot' \
robots.txt urls.txt \
badbot,anybot
Testing robots.txt for agent names: badbot,anybot
not allowed:    https://www.example.com/
```

[NUTCH-2801] RobotsRulesParser command-line checker to use http.robots.agents as fall-back

---

build.xml

(thanks to @lewismc for the first version of the patch)
- spotbugs static code analysis is called on-demand as ant target "spotbugs"
- first call will download the spotbugs tool and "install" it in lib/
- creates spotbugs report ("build/nutch-spotbugs.html") covering Nutch core and plugins

[NUTCH-2816] Add Spotbugs target to ant build

---

src/plugin/protocol-file/src/java/org/apache/nutch/protocol/file/FileResponse.java
src/plugin/protocol-ftp/src/java/org/apache/nutch/protocol/ftp/FtpResponse.java

- replace check whether URL path and file are identical by check whether URL has a query
- clean up code and improve log messages

[NUTCH-2817] Avoid check for equality of URL path and file part using == / !=

---

.gitignore
default.properties
src/plugin/any23/build-ivy.xml
src/plugin/exchange-jexl/build-ivy.xml
src/plugin/index-geoip/build-ivy.xml
src/plugin/indexer-elastic/build-ivy.xml
src/plugin/indexer-kafka/build-ivy.xml
src/plugin/indexer-rabbit/build-ivy.xml
src/plugin/indexer-solr/build-ivy.xml
src/plugin/lib-htmlunit/build-ivy.xml
src/plugin/lib-rabbitmq/build-ivy.xml
src/plugin/lib-selenium/build-ivy.xml
src/plugin/parse-tika/build-ivy.xml
src/plugin/parsefilter-naivebayes/build-ivy.xml
src/plugin/protocol-interactiveselenium/build-ivy.xml
src/plugin/protocol-selenium/build-ivy.xml
src/plugin/publish-rabbitmq/build-ivy.xml
src/plugin/scoring-similarity/build-ivy.xml

Address:
- NUTCH-2671 Upgrade ant ivy library
- NUTCH-2697 Upgrade Ivy to fix the issue of an unset packaging.type property
- NUTCH-2669 Reliable solution for javax.ws packaging.type
- NUTCH-2672 Ant build erronously installs *-test.jar instead *.jar for target "nightly"
Requires that the ivy cache is wiped out (eg. `rm -rf ~/.ivy2/cache`) because the cache of ivy 2.5.0 is not backward compatible to older ivy versions. Ant builds fail otherwise.
Includes:
- upgrade Ivy (2.4.0 -> 2.5.0)
- upgrade all plugins build-ivy.xml (preparing lists of dependencies registered in plugin.xml)
- to use the ivy jar 2.5.0 installed in $NUTCH_HOME/ivy/
- only download the ivy jar if it's not found there

NUTCH-2697 Upgrade Ivy to 2.5.0

---

src/java/org/apache/nutch/net/protocols/HttpDateFormat.java
src/test/org/apache/nutch/net/protocols/TestHttpDateFormat.java

- reset time zone to GMT after parsing a date
- add unit test

NUTCH-2814 HttpDateFormat's internal time zone may change after parsing a date

---

build.xml

- make target "clean-cache" depend on "ivy-init" so that ivy-related resources are defined

NUTCH-2829 Fix ant target "clean-cache"

---

conf/tika-config.xml.template
src/java/org/apache/nutch/fetcher/Fetcher.java
src/java/org/apache/nutch/util/MimeUtil.java

- add method in MimeUtil to set MimeTypesReader pool size
- actually adjust pool size to number of Fetcher threads / 2
(minimum pool size is 10 in case there are less than 20 Fetcher threads)
- double pool size (10 -> 20) of Tika XMLReaderUtils in tika-config.xml

NUTCH-2582 Set pool size of XML SAX parsers used for MIME detection in Tika

---

ivy/ivy.xml

PR addresses https://issues.apache.org/jira/browse/NUTCH-2836
I looked for deprecation and none exists.
All tests pass locally. 
3 rounds of crawling executed with >15k seed list. No issues were observed.

NUTCH-2836 Upgrade various commons dependencies

---

.gitignore
build.xml

- install spotbugs into to ivy/spotbugs-x.x.x/
- upgrade to Spotbugs 4.2.0
- move task definition into spotbugs target, otherwise running download/installation and bug spotting together fails

NUTCH-2819 Move spotbugs "installation" directory to avoid that spotbugs is shipped in Nutch runtime

---

conf/suffix-urlfilter.txt.template

add more excluded file suffixes for
- images
- audio and video formats
- software packages and archives
- fonts

NUTCH-2845 Complete rules of urlfilter-suffix

---

src/java/org/apache/nutch/crawl/Generator.java
src/java/org/apache/nutch/indexer/IndexingJob.java
src/java/org/apache/nutch/segment/SegmentReader.java
src/java/org/apache/nutch/tools/DmozParser.java

This PR addresses https://issues.apache.org/jira/browse/NUTCH-2851
I chose the following proposed fix...
Create a constant Random in the offending class
```
private static final Random RANDOM = new Random();
```
We then reuse as follows
```
RANDOM.nextInt();
```
This way, no new instances are created.

NUTCH-2851 Random object created and used only once

---

conf/nutch-default.xml
conf/protocols.txt.template
src/plugin/urlnormalizer-basic/src/test/org/apache/nutch/net/urlnormalizer/basic/TestBasicURLNormalizer.java
src/plugin/urlnormalizer-protocol/data/protocols.txt
src/plugin/urlnormalizer-protocol/src/java/org/apache/nutch/net/urlnormalizer/protocol/ProtocolURLNormalizer.java
src/plugin/urlnormalizer-protocol/src/java/org/apache/nutch/net/urlnormalizer/protocol/package-info.java
src/plugin/urlnormalizer-protocol/src/test/org/apache/nutch/net/urlnormalizer/protocol/TestProtocolURLNormalizer.java

(note: to avoid merge conflicts, this PR includes #575)
In order to address NUTCH-2859 host names starting with `*.` (in the config file `protocols.txt` or in the string rules) are matched as suffixes: `*.example.org` matches `example.org`, `www.example.org`, `www.subdomain.example.org`, etc.
Additional improvements:
- allow to read config file protocols.txt from hdfs:// or any file system supported by Hadoop - useful if the list of host or domains requiring normalization is large or changes often
- add Javadoc package documentation
- document configuration properties in nutch-default.xml
- reduce the memory footprint by deduplicating protocol strings, so that same protocol values are references to same objects

NUTCH-2859: urlnormalizer-protocol: allow to normalize domains

---

conf/protocols.txt.template
src/plugin/urlnormalizer-basic/src/test/org/apache/nutch/net/urlnormalizer/basic/TestBasicURLNormalizer.java
src/plugin/urlnormalizer-protocol/src/java/org/apache/nutch/net/urlnormalizer/protocol/ProtocolURLNormalizer.java
src/plugin/urlnormalizer-protocol/src/test/org/apache/nutch/net/urlnormalizer/protocol/TestProtocolURLNormalizer.java

- if URL includes a port the protocol is not normalized
Note that
- urlnormalizer-basic removes default ports:  `https://example.com:443/` is normalized to `https://example.com/` - by chaining normalizers there is no need to handle default ports in urlnormalizer-protocol
- non-default ports can always be mapped by urlnormalizer-regex, there shouldn't be many, so the price of more complex rules and slower execution is acceptable

NUTCH-2858 urlnormalizer-protocol: URL port is lost during normalization

---

docker/Dockerfile
docker/README.md

This PR addresses https://issues.apache.org/jira/browse/NUTCH-2864
Using the Alpine Linux base is supposed to create a smaller overall image footprint...

NUTCH-2864 Upgrade Dockerfile to use JDK 11

---

build.xml

- avoid needless warning by moving taskdef into task element

NUTCH-2899 Remove needless warning about missing o/a/rat/anttasks/antlib.xml

---

src/java/org/apache/nutch/util/StringUtil.java
src/plugin/indexer-elastic/src/java/org/apache/nutch/indexwriter/elastic/ElasticIndexWriter.java
src/plugin/indexer-rabbit/src/java/org/apache/nutch/indexwriter/rabbit/RabbitIndexWriter.java
src/plugin/indexer-solr/src/java/org/apache/nutch/indexwriter/solr/SolrIndexWriter.java
src/plugin/protocol-httpclient/src/java/org/apache/nutch/protocol/httpclient/HttpBasicAuthentication.java
src/test/org/apache/nutch/util/TestStringUtil.java

- add utility methods (StringUtil) to mask password strings or passwords in strings
- mask passwords in log output of index writers (Elasticsearch, Solr, RabbitMQ)
- mask password in trace log of protocol-httpclient when using basic authentication

NUTCH-2905 Mask sensitive strings in log output of index writers

---

conf/log4j2.xml
src/bin/nutch

- `nutch.log` replaces `hadoop.log` as default log file name
- file rotation patterns only match `nutch.log` as log file name
- checking on start-up whether the log file(s) need to be rotated

NUTCH-2916 Fix log file rotation / rename default log file

---

src/plugin/language-identifier/build-ivy.xml
src/plugin/language-identifier/build.xml

This PR finishes off and therefore supersedes https://github.com/apache/nutch/pull/233 in a post-[NUTCH-2891](https://issues.apache.org/jira/browse/NUTCH-2891)/ b0cbea5 world :)
@sebastian-nagel I have no examples which would validate [NUTCH-1397](https://issues.apache.org/jira/browse/NUTCH-1397). Do you?

NUTCH-2449 Replace Tika LanguageIdentifier in language-identifier

---

build.xml
src/java/org/apache/nutch/crawl/CrawlDbReader.java
src/java/org/apache/nutch/parse/ParserChecker.java
src/java/org/apache/nutch/plugin/PluginManifestParser.java
src/java/org/apache/nutch/plugin/PluginRepository.java
src/java/org/apache/nutch/plugin/URLStreamHandlerFactory.java
src/java/org/apache/nutch/util/CrawlCompletionStats.java
src/java/org/apache/nutch/util/NutchJob.java
src/java/org/apache/nutch/util/NutchTool.java
src/java/org/apache/nutch/util/SitemapProcessor.java
src/java/org/apache/nutch/util/domain/DomainStatistics.java
src/plugin/any23/src/java/org/apache/nutch/any23/Any23IndexingFilter.java
src/plugin/any23/src/java/org/apache/nutch/any23/Any23ParseFilter.java
src/plugin/build.xml
src/plugin/indexer-csv/src/java/org/apache/nutch/indexwriter/csv/CSVIndexWriter.java
src/plugin/indexer-rabbit/src/java/org/apache/nutch/indexwriter/rabbit/RabbitIndexWriter.java
src/plugin/protocol-foo/build.xml
src/plugin/protocol-foo/ivy.xml
src/plugin/protocol-foo/plugin.xml
src/plugin/protocol-foo/src/java/org/apache/nutch/protocol/foo/Foo.java
src/plugin/protocol-foo/src/java/org/apache/nutch/protocol/foo/Handler.java

This issue addresses [NUTCH-2429](https://issues.apache.org/jira/browse/NUTCH-2429). Some notes
* supersedes #222 by updating everything which was done there (excellent work @HiranChaudhuri )
* incorporates @sebastian-nagel work a la  [/sebastian-nagel/nutch/tree/NUTCH-2429](https://github.com/sebastian-nagel/nutch/commit/e589f05ef42486892427d347ecd10abfa9e380d7)
* organizes the imports for each Class touched in this pull request
* addresses a couple of rogue Classes which declared `public static final Logger` --> `private static final Logger`
* adds `protocol-foo` to the `ant eclipse` target so it is included in the Eclipse development environment
* formats code where necessary using the Nutch eclipse formatting
* addresses improvements to Javadoc where relevant
I've run this on trace …

NUTCH-2429 Fix Plugin System to allow protocol plugins to bundle their URLStreamHandlers

---

conf/nutch-default.xml
src/java/org/apache/nutch/fetcher/Fetcher.java

Sleep for a configurable delay (fetcher.threads.start.delay) before starting the next Fetcher thread to avoid that resources (DNS, Tika XML parser pools) are temporarily exhausted when Fetcher threads fetch the first pages simultaneously
The default delay (10 milliseconds) practically does not impact the behavior/performance of Fetcher - 100 threads are started per second. By choosing a longer delay (500 milliseconds) all Tika warnings about the SAXParser pool size disappeared.

NUTCH-2929 Fetcher: start threads slowly to avoid that resources are temporarily exhausted

---

conf/nutch-default.xml
src/java/org/apache/nutch/fetcher/FetchItemQueues.java
src/java/org/apache/nutch/fetcher/FetcherThread.java
src/java/org/apache/nutch/protocol/RobotRulesParser.java
src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpRobotRulesParser.java

- add properties
- `http.robots.503.defer.visits` :
enable/disable the feature (default: enabled)
- `http.robots.503.defer.visits.delay` :
delay to wait before the next trial to fetch the properties
(default: wait 5 minutes)
- `http.robots.503.defer.visits.retries` :
max. number of retries before giving up and dropping all URLs from the given host / queue
(default: give up after the 3rd retry, ie. after 4 attempts)
- handle HTTP 5xx in robots.txt parser
- handle delay, retries and dropping queues in Fetcher
Stop queuing fetch items if timelimit is reached
- re-queuing items where the robots.txt request returned a 5xx
- redirects (http.redirect.max > 0) or
- outlinks (fetcher.follow.outlinks.depth > 0)
In a first version, I forgot to verify whether the Fetcher timelimit …

NUTCH-2573 Suspend crawling if robots.txt fails to fetch with 5xx status

---

conf/nutch-default.xml
src/java/org/apache/nutch/fetcher/FetchItemQueues.java

Fetcher to slow down fetching from hosts where requests fail repeatedly with exceptions or HTTP status codes mapped to ProtocolStatus.EXCEPTION (HTTP 403 Forbidden, 429 Too many requests, 5xx server errors, etc.)

NUTCH-2946 Fetcher: optionally slow down fetching from hosts with repeated exceptions

---

src/java/org/apache/nutch/parse/ParserChecker.java
src/java/org/apache/nutch/plugin/Extension.java
src/java/org/apache/nutch/plugin/ExtensionPoint.java
src/java/org/apache/nutch/plugin/PluginManifestParser.java
src/java/org/apache/nutch/plugin/PluginRepository.java
src/java/org/apache/nutch/plugin/URLStreamHandlerFactory.java
src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpBase.java
src/plugin/protocol-foo/plugin.xml
src/plugin/protocol-okhttp/ivy.xml
src/plugin/protocol-okhttp/plugin.xml
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttp.java
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttpResponse.java

I ended up producing this PR as a result of investigating NUTCH-2936. This PR does not fix NUTCH-2936.
The problem is that the [trustAllSslSocketFactory](https://github.com/apache/nutch/blob/master/src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttp.java#L129) variable is `null` when passed into `okhttp3.OkHttpClient.Builder.sslSocketFactory`.
I have not yet tried to verify if running protocol-okhttp is distributed mode. I can try that early next week. It might be worthwhile us reverting NUTCH-2429.

NUTCH-2936 Early registration of URL stream handlers provided by plugins may fail Hadoop jobs running in distributed mode

---

src/java/org/apache/nutch/plugin/Extension.java
src/java/org/apache/nutch/plugin/Plugin.java
src/java/org/apache/nutch/plugin/PluginRepository.java
src/java/org/apache/nutch/plugin/URLStreamHandlerFactory.java
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttp.java

Fixes to address the failing of Nutch jobs in (pseudo-)distributed mode. Implements:
- caching of URLStreamHandlers per protocol to avoid that handlers are created anew
- enforce routing of standard protocols (http, https, file, jar) to handlers implemented by the JVM
- utilizes the URLStreamHandler cache
- fixes NUTCH-2936 (verified in pseudo-distributed mode)
Also:
- code improvements in classes of the package "org.apache.nutch.plugin"
- use `Class<?>` and remove suppressions of warnings
- javadocs: fix typos
- remove superfluous white space
- autoformat using code style template
- protocol-okhttp: initialize SSLContext not in a static code block (SSLContext is used to ignore SSL/TLS certificate verification): this was the initial fix for the needless warning in parsechecker even in …

NUTCH-2936 / NUTCH-2949 URLStreamHandler may fail jobs in distributed mode

---

ivy/ivy.xml
src/plugin/publish-rabbitmq/ivy.xml

Upgrade of core dependencies
- Hadoop 3.1.3 -> 3.3.3
- log4j 2.17.0 -> 2.17.2
- and some more
Note: I've observed that some unit tests are failing with same/similar errors than observed in NUTCH-2936. Eventually, this PR needs to be rebased on top of #733.

NUTCH-2952 Upgrade core dependencies

---

conf/nutch-default.xml
src/plugin/index-geoip/ivy.xml
src/plugin/index-geoip/plugin.xml
src/plugin/index-geoip/src/java/org/apache/nutch/indexer/geoip/GeoIPDocumentCreator.java
src/plugin/index-geoip/src/java/org/apache/nutch/indexer/geoip/GeoIPIndexingFilter.java
src/plugin/indexer-solr/schema.xml

- upgrade to geoip2 3.0.1
- exclude transitive dependencies (Jackson) provided as Nutch core deps
- upgrade Jackson to 2.13.2
- read also GeoLite2-*.mmdb files
- review index field names in plugin and Nutch Solr schema:
- fix typos in field names
- remove unused fields from schema
- simplify `addIfNotNull` methods

NUTCH-2956 index-geoip: dependency upgrades and improvements

---

conf/nutch-default.xml
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttp.java
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttpResponse.java

- add configuration property `http.connection.pool.okhttp` to configure the number of connection pools, their size and the keep-alive time of the pooled connections
- create as many clients as pools are configured, each client holding one pool
- distribute connections by target host name over clients

NUTCH-2896 Protocol-okhttp: make connection pool configurable

---

src/java/org/apache/nutch/fetcher/FetchItemQueues.java
src/java/org/apache/nutch/fetcher/QueueFeeder.java

Fetcher: keep state of empty but stateful fetch queues unless queue feeder is finished in order to ensure politeness
- next fetch time not yet reached
- non-zero exception counter and queue feeder still
adding new fetch items to queues
Only if the the queue feeder is finished and no more new fetch items are added, these queues can finally removed.
Note: this PR needs to be adapted to #728 (NUTCH-2946) or vice verse whichever is merged first. The state of queues needs also preserved in case fetcher.max.exceptions.per.queue == -1 but fetcher.exceptions.per.queue.delay != -1.

NUTCH-2947 Fetcher: keep state of empty fetch queues unless queue feeder is finished

---

conf/nutch-default.xml
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/CIDR.java
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/IPFilterRules.java
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttp.java
src/plugin/protocol-okhttp/src/test/org/apache/nutch/protocol/okhttp/TestBadServerResponses.java
src/plugin/protocol-okhttp/src/test/org/apache/nutch/protocol/okhttp/TestIPAddressFiltering.java
src/plugin/protocol-okhttp/src/test/org/apache/nutch/protocol/okhttp/TestProtocolOkHttp.java
src/test/org/apache/nutch/protocol/AbstractHttpProtocolPluginTest.java

Implement filter by IP address for protocol-okhttp, configurable via include/exclude rules as list of IP address, CIDR notation
or predefined IP ranges (localhost, loopback, sitelocal).

NUTCH-2930 Protocol-okhttp: implement IP filter

---

LICENSE-binary
NOTICE-binary
build.xml
ivy/ivy.xml
src/plugin/indexer-solr/ivy.xml
src/plugin/indexer-solr/plugin.xml
src/plugin/urlfilter-automaton/ivy.xml
src/plugin/urlfilter-automaton/plugin.xml

- upgrade Hadoop 3.3.3 -> 3.3.4
- adapt ivy retrieve pattern to optionally include the `classifier`
(used in Hadoop deps to differentiate between architecture: x86_64 vs. aarch_64)
- upgrade Nutch core dependencies
httpcore-nio 4.4.9 -> 4.4.14
cxf 2.9.0 -> 2.9.1
commons-jexl3 3.2.1 -> 3.3
log4j 2.17.2 -> 2.18.0
t-digest 3.2 -> 3.3
- upgrade indexer-solr dependencies:
- Solr 8.5.1 -> 8.11.2
- httpmime 4.5.10 -> 4.5.13
- httpcore 4.4.12 -> 4.4.15
- upgrade urlfilter-automaton to depend on dk.brics automaton 1.12-4
- upgrade dependency-check ant plugin
NUTCH-2843 Duplicate declaration of dependencies in ivy.xml
- remove duplicated dependencies: commons-collections4 and httpclient
- move Maven POM creation into separate target to reproduce issue

NUTCH-2963 Upgrade dependencies before release of 1.19

---

build.xml

- pass --no-module-directories to javadoc target when building on JDK 11
- remove obsolete condition to fail javadoc builds on JDK 7u25 and earlier

NUTCH-2969 Javadoc: Javascript search is not working when built on JDK 11

---

docker/.dockerfilelintrc
docker/Dockerfile
docker/README.md
docker/config/supervisord_startserver.conf
docker/config/supervisord_startserver_webapp.conf

This PR includes everything from #691 rebased to the recent master and sqashed into a single commit. It also includes
- a fix to make the arg instructions (eg. `--build-arg BUILD_MODE=1`) working, see [comment in #691](https://github.com/apache/nutch/pull/691#issuecomment-925304439)
- installation of the WebApp from the separate repository and running it via `mvn jetty:run -Djetty.port=<WEBAPP_PORT>`
So far, I've successfully tested this PR
- using all BUILD_MODEs: 0 (default if not set), 1 and 2
- running the resulting images as containers
- for build mode 0: run some Nutch commands
- for build mode 2 (server + webapp): configure run a small crawl
- for build mode 1 (server): run external webapp to configure and run a crawl
- crawls where successful with some work-arounds required …

NUTCH-2883 Provide means to run server and webapp as persistent services in Docker container

---

build.xml

- [touch](https://ant.apache.org/manual/Tasks/touch.html) using epoche millis instead of datetime to specify the touch time
- add comment to explain why configuration templates are touched back in time

NUTCH-2974 Ant build fails with "Unparseable date" on certain platforms

---

README.md
src/plugin/lib-htmlunit/ivy.xml
src/plugin/lib-htmlunit/plugin.xml
src/plugin/lib-selenium/ivy.xml
src/plugin/lib-selenium/plugin.xml
src/plugin/lib-selenium/src/java/org/apache/nutch/protocol/selenium/HttpWebClient.java
src/plugin/protocol-interactiveselenium/src/java/org/apache/nutch/protocol/interactiveselenium/handlers/DefaultClickAllAjaxLinksHandler.java

- Disabled phantomJS driver as it was causing problems casting TakeScreenshot to HtmlUnitWebDriver and the project has been archived since 2018
- Improved README setup instructions for IntelliJ
The following libraries were added as part of the selenium-java and htmlunit upgrades. They are all Apache 2.0, MIT or EDL.
async-http-client
async-http-client-netty-utils
auto-common
auto-service
auto-service-annotations
checker-qual
dec
failsafe
failureaccess
htmlunit-xpath
jakarta.activation
jcommander
jtoml
listenablefuture
netty-buffer
netty-codec
netty-codec-http
netty-codec-socks
netty-common
netty-handler
netty-handler-proxy
netty-reactive-streams
netty-resolver
netty-transport
netty-transport-classes-epoll
netty-transport-classes-kqueue
netty-transport-native-epoll …

NUTCH-2980: Upgraded Selenium to 4.7.2 + HTMLUnit

---

src/java/org/apache/nutch/crawl/Generator.java

- pass forward params `norm` and `maxNumSegments`
- fix typos in Javadoc

NUTCH-2982 Generator: parameter for URL normalization not passed forward

---

src/java/org/apache/nutch/segment/SegmentMerger.java
src/java/org/apache/nutch/tools/arc/ArcRecordReader.java
src/plugin/urlfilter-suffix/src/java/org/apache/nutch/urlfilter/suffix/SuffixURLFilter.java

- fix Javadoc issues when building with JDK 17
- note: the remaining 100 warnings are all about missing Javadocs for methods and variables

NUTCH-2972 Javadoc build fails using JDK 17

---

ivy/ivy.xml
src/plugin/lib-http/src/test/org/apache/nutch/protocol/http/api/TestRobotRulesParser.java

in addition,
- update Javadoc and improve code formatting of robots.txt unit tests
- fix robots.txt unit tests to reflect changes in   crawler-commons due to RFC 9309 compliance and merging of rule groups   (see https://www.rfc-editor.org/rfc/rfc9309.html#section-2.2.1)
- mark unit tests using now deprecated API endpoints as deprecated

 NUTCH-2995 Upgrade to crawler-commons 1.4

---

conf/nutch-default.xml
src/java/org/apache/nutch/protocol/RobotRulesParser.java
src/plugin/lib-http/src/test/org/apache/nutch/protocol/http/api/TestRobotRulesParser.java

Note: because NUTCH-2996 requires the upgrade to crawler-commons 1.4, all changes of NUTCH-2995 are included. Only bc5326d contains the changes for NUTCH-2996.
- split and lowercase agent names (if multiple) at configuration time and pass as collection to SimpleRobotRulesParser
- update RobotRulesParser command-line help
- update unit tests to use new API

NUTCH-2996 Use new SimpleRobotRulesParser API entry point crawler-commons 1.4

---

src/plugin/lib-selenium/src/java/org/apache/nutch/protocol/selenium/HttpWebClient.java

…ust the inner body element.
Thanks for your contribution to [Apache Nutch](https://nutch.apache.org/)! Your help is appreciated!
- and placed in front of your commit messages surrounded by square brackets (`[NUTCH-XXXX] Issue or pull request title`)
* Java source code follows [Nutch Eclipse Code Formatting …

NUTCH-3000 - the selenium protocol should return the full html, not just the inner body

---

src/java/org/apache/nutch/plugin/Plugin.java
src/java/org/apache/nutch/util/NutchJob.java

- deprecate constructor of NutchJob
- remove deprocated call to Object.finalize() from Plugin.finalize()

NUTCH-2897 Do not supress deprecated API warnings

---

src/java/org/apache/nutch/metadata/CaseInsensitiveMetadata.java
src/java/org/apache/nutch/metadata/Metadata.java
src/java/org/apache/nutch/metadata/SpellCheckedMetadata.java
src/java/org/apache/nutch/net/protocols/Response.java
src/plugin/protocol-http/src/test/org/apache/nutch/protocol/http/TestResponse.java
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttpResponse.java
src/plugin/protocol-okhttp/src/test/org/apache/nutch/protocol/okhttp/TestResponse.java

- implement class CaseInsensitiveMetadata providing case-insensitive metadata look-ups (but no spell-checking)
- use CaseInsensitiveMetadata to hold HTTP header metadata in in the class OkHttpResponse of protocol-okhttp
- add unit tests to prove the fix (and also case-insensitive look-ups and spell-checking in protocol-http)
The unit tests also include a deactivated benchmark: storing HTTP headers in CaseInsensitiveMetadata is approx. 10% faster than in SpellCheckedMetadata.

NUTCH-3002 Protocol-okhttp HttpResponse: HTTP header metadata lookup should be case-insensitive

---

conf/nutch-default.xml
src/java/org/apache/nutch/protocol/RobotRulesParser.java
src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpRobotRulesParser.java

- follow multiple redirects when fetching robots.txt
- number of followed redirects is configurable by the property `http.robots.redirect.max` (default: 5)
- improvements in RobotRulesParser's robots.txt test utility
- bug fix: the passed agent names need to be transferred to the property http.robots.agents earlier, before the protocol plugins are configured
- more verbose debug logging

NUTCH-2990 HttpRobotRulesParser to follow 5 redirects as specified by RFC 9309

---

src/java/org/apache/nutch/segment/SegmentReader.java

Use UTF-8 as fall-back encoding when stringifying the content of unparsed documents.

NUTCH-3012 SegmentReader when dumping with option -recode: NPE on unarsed documents

---

src/java/org/apache/nutch/parse/ParseSegment.java
src/test/org/apache/nutch/parse/TestParseSegment.java

Thanks for your contribution to [Apache Nutch](https://nutch.apache.org/)! Your help is appreciated!
- and placed in front of your commit messages surrounded by square brackets (`[NUTCH-XXXX] Issue or pull request title`)
* Java source code follows [Nutch Eclipse Code Formatting …

NUTCH-3020 -- ParseSegment should check for okhttp's truncation flag

---

src/plugin/urlfilter-fast/src/java/org/apache/nutch/urlfilter/fast/FastURLFilter.java

and support gzipped input
See https://issues.apache.org/jira/browse/NUTCH-3017

[NUTCH-3017] Allow fast-urlfilter to load from HDFS/S3 

---

conf/nutch-default.xml
src/plugin/urlfilter-fast/README.md
src/plugin/urlfilter-fast/src/java/org/apache/nutch/urlfilter/fast/FastURLFilter.java
src/plugin/urlfilter-fast/src/test/org/apache/nutch/urlfilter/fast/TestFastURLFilter.java

Checks the length of the query and path elements of a URL. 
see https://issues.apache.org/jira/browse/NUTCH-3025

[NUTCH-3025] urlfilter-fast to filter based on the length of the URL

---

docker/Dockerfile

Alpine is using ash shell by default which results in an not set JAVA_HOME environment variable
Sry, there is no issue reported atm on issues.apache.org - never the less, it is one I'm facing to

Update Dockerfile / JAVA_HOME

---

src/plugin/indexer-elastic/howto_upgrade_es.md
src/plugin/indexer-elastic/ivy.xml
src/plugin/indexer-elastic/plugin.xml
src/plugin/indexer-elastic/src/java/org/apache/nutch/indexwriter/elastic/ElasticIndexWriter.java

This PR downgrades the ES client to version 7.10.2 which is licensed under ASF 2.0 - it's a quick fix to stay compatible with ASF policies.
Not yet tested: indexing into ES
To be done: update the LICENSE and NOTICE files. I'll do this as part of a separate issue NUTCH-3035.

NUTCH-3008 indexer-elastic: downgrade to ES 7.10.2 to address licensing issues

---

LICENSE-binary
NOTICE-binary

Update the license and notice files of dependencies  included as binary jar files in the binary release.

NUTCH-3035 Update license and notice file for release of 1.20

---

build.xml
conf/nutch-default.xml
src/plugin/build.xml
src/plugin/index-arbitrary/build.xml
src/plugin/index-arbitrary/ivy.xml
src/plugin/index-arbitrary/plugin.xml
src/plugin/index-arbitrary/src/java/org/apache/nutch/indexer/arbitrary/ArbitraryIndexingFilter.java
src/plugin/index-arbitrary/src/java/org/apache/nutch/indexer/arbitrary/package-info.java
src/plugin/index-arbitrary/src/test/org/apache/nutch/indexer/arbitrary/Echo.java
src/plugin/index-arbitrary/src/test/org/apache/nutch/indexer/arbitrary/Multiplier.java
src/plugin/index-arbitrary/src/test/org/apache/nutch/indexer/arbitrary/TestArbitraryIndexingFilter.java

This is the initial code for an arbitrary indexing filter, NUTCH-3032.
It could be helpful to let end users manipulate information at indexing time with their own code without the need for writing their own indexing plugin. I mentioned this on the dev mailing list (https://www.mail-archive.com/dev@nutch.apache.org/msg31190.html) with some description of my work in progress.
One potential use is to address some of the same concerns that NUTCH-585 discusses regarding an alternative approach to picking and choosing which content to index, but this approach would allow making index time decisions, rather than setting the configuration for all content at the start of the indexing run.
Ideally a solution to NUTCH-585 would work at parse time, but this index time code still has potential uses …

NUTCH-3032 Code for an ArbitraryIndexingFilter to index values resolved by user POJO code at index time

---

src/java/org/apache/nutch/plugin/URLStreamHandlerFactory.java

Pass ftp:// URLs to the standard JVM URLStreamHandler

NUTCH-3039 Failure to handle ftp:// URLs

---

src/java/org/apache/nutch/crawl/Generator.java

- add counters URL_FILTERS_REJECTED and URL_FILTER_EXCEPTION
- simplify logging statement
- remove unnecessary cast

NUTCH-3043 Generator: count URLs rejected by URL filters

---

src/plugin/protocol-http/src/test/org/apache/nutch/protocol/http/TestResponse.java
src/plugin/protocol-okhttp/src/test/org/apache/nutch/protocol/okhttp/TestResponse.java
src/test/org/apache/nutch/protocol/AbstractHttpProtocolPluginTest.java

- use random free ephemeral port in AbstractHttpProtocolPluginTest
- store used port in field "serverPort", inherited by plugin tests
- use serverPort to sleep longer until server is up and set its port number

NUTCH-3066 Protocol plugin unit tests fail randomly

---

CHANGES.md
ivy/mvn.template

[View updated Changelog in GitHub](https://github.com/sebastian-nagel/nutch/blob/NUTCH-3065-changelog-markdown/CHANGES.md)

NUTCH-3065 Format changelog as markdown

---

conf/nutch-default.xml
src/java/org/apache/nutch/net/protocols/Response.java
src/plugin/lib-http/src/java/org/apache/nutch/protocol/http/api/HttpBase.java
src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttp.java

Adds property `store.protocol.versions` - if true, protocol-okhttp records protocol versions and related in response metadata:
- `_protocol_versions_` holds the HTTP and SSL/TLS versions
- `_cipher_suites_` holds the SSL/TLS cipher suites
Minor cleanup: do not rely on the system encoding in method getBytes() when storing verbatim HTTP headers. Use iso-8859-1 (HTTP headers should be ASCII only).

NUTCH-3062 protocol-okhttp: optionally record HTTP and SSL/TLS versions

---

src/plugin/lib-regex-filter/src/java/org/apache/nutch/urlfilter/api/RegexURLFilterBase.java
src/plugin/urlfilter-automaton/src/java/org/apache/nutch/urlfilter/automaton/AutomatonURLFilter.java
src/plugin/urlfilter-fast/src/java/org/apache/nutch/urlfilter/fast/FastURLFilter.java
src/plugin/urlfilter-fast/src/test/org/apache/nutch/urlfilter/fast/TestFastURLFilter.java
src/plugin/urlfilter-regex/src/java/org/apache/nutch/urlfilter/regex/RegexURLFilter.java

Let urlfilter-regex, urlfilter-automaton and urlfilter-fast log the name of the rules file. Also log the number of rules read from the file.
Cleanup (Javadoc) comments in the modified classes.

NUTCH-3061 URL filters to log name of the rules file

---

conf/nutch-default.xml
src/java/org/apache/nutch/fetcher/FetchItemQueue.java
src/java/org/apache/nutch/fetcher/FetchItemQueues.java
src/java/org/apache/nutch/fetcher/Fetcher.java

Address NUTCH-3067:
1. do not keep every stateful queue: drop queues which have a low exception count after a configurable amount of time. If a second URL from the same host/domain/IP is fetched after a considerably long time span (eg. 30 minutes), the effect on performance and politeness should be negligible.
This is configured by `fetcher.exceptions.per.queue.clear.after` (default 30 minutes): if this time has elapsed after the next fetch time in the queue, that is in addition to any delay defined by the exponential backoff, empty queues are dropped.
2. reviewed and improved the handling of the exponential backoff in [FetchQueues.checkExceptionThreshold](https://nutch.apache.org/documentation/javadoc/api/org/apache/nutch/fetcher/FetchItemQueues.html#checkExceptionThreshold(java.lang.Stri …

NUTCH-3067 Improve performance of FetchItemQueues if error state is preserved

---

.github/workflows/master-build.yml

PR for https://issues.apache.org/jira/browse/NUTCH-3084
This does fundamentally change how the `tests` are executed. By default, we now no longer run tests. We only run tests if changes have been made to 
- the [core](https://github.com/apache/nutch/tree/master/src/java) or [core tests](https://github.com/apache/nutch/tree/master/src/test), or [testresources](https://github.com/apache/nutch/tree/master/src/testresources), or
- [plugins](https://github.com/apache/nutch/tree/master/src/plugin)

NUTCH-3084 Improve CI by filtering and separating plugin and core test executiion

---

build.xml
src/test/org/apache/nutch/segment/TestSegmentMerger.java
src/test/org/apache/nutch/segment/TestSegmentMergerCrawlDatums.java

- introduce target "test-full" which executes all unit tests, even slow ones
- slow unit tests are only run if the system property "test.include.slow" is true (it is set to true by the target "test-full")
- a solution based on JUnit tags isn't possible since we use Ant and are still on JUnit 4

NUTCH-2771 Tests in nightly builds: skip long runners

---

.github/workflows/master-build.yml

This PR improves the logic of conditional steps in the Github workflow:
- all tests are executed if any of build configuration, core or plugins code changed
- core tests if there are only changes in core
- plugin tests if there are only changes in the plugins source folder

NUTCH-3094 Github tests to run if build configuration changes

---

src/bin/nutch

Adds the command *robotsparser* to bin/nutch, invoking the main method of org.apache.nutch.protocol.RobotRulesParser

NUTCH-3083 Add RobotRulesParser to bin/nutch

---

src/java/org/apache/nutch/segment/SegmentReader.java

SegmentReaders dump and get tools do now check whether a segment subdirectory exists before adding it as input. A warning is shown if the subdirectory does not exist but is not excluded via one of the general options (-nogenerate, etc.)

NUTCH-3079 Dumping a segment fails unless it has been fetched and parsed

---

src/java/org/apache/nutch/fetcher/FetchItemQueues.java
src/java/org/apache/nutch/fetcher/Fetcher.java
src/java/org/apache/nutch/fetcher/QueueFeeder.java

- Fetcher signals QueueFeeder (via FetchItemQueues) to stop queuing and waits 1.5 seconds for this to happen
- QueueFeeder (if still alive) discards remaining items with QueuingStatus "HIT_BY_TIMEOUT"
- add number of items skipped by QueueFeeder to "FetcherStatus" counters
- mark variables defined in FetchItemQueues but accessed from QueueFeeder thread as "volatile"
- minor code cleanups
The solution was tested the following way:
- the local Apache httpd was configured to respond with "HTTP 429 Too many requests" on a specific path
- a seed list containing URLs with mostly URLs on this path on localhost was created and converted into a segment using the "freegen" tool
- Fetcher was run with a single fetcher thread, a short queue and a high timeout divisor (= short timeout):
```
nutch …
```

NUTCH-3072 Fetcher to stop QueueFeeder if aborting with "hung threads"

---

src/plugin/language-identifier/ivy.xml
src/plugin/language-identifier/plugin.xml

When running Apache Nutch 1.20 on a distributed Hadoop cluster with the language-identifier plugin enabled, a class loader conflict occurs during the parse process. This results in the following error:
2025-02-24 08:58:59,152 INFO mapreduce.Job: Task Id : attempt_1740061418437_0135_m_000001_0, Status : FAILED
Error: loader constraint violation: when resolving method 'org.slf4j.ILoggerFactory org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()' the class loader org.apache.nutch.plugin.PluginClassLoader @4c5228e7 of the current class, org/slf4j/LoggerFactory, and the class loader 'app' for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature (org.slf4j.LoggerFactory is in unnamed module of …

NUTCH-3108 Fix SLF4J Class Loader Conflict in language-identifier

---

conf/adaptive-host-specific-intervals.txt.template
src/java/org/apache/nutch/crawl/AdaptiveFetchSchedule.java

1) The loop in setHostSpecificIntervals is cleaned up and if max interval in the config is set to default, it is treated correctly.
2) The functions getMinInterval and getMaxInterval are respectively renamed to getCustomMinInterval and getCustomMaxInterval and now return null if no custom interval has been set for the given URL's hostname. If one of them returns null after it is called, then the corresponding default value will be used to bound the calculated interval.
3) The custom interval values in the config are now allowed to equal the default values. For example, if the default min interval is 7200 then in the config file "0", "default" and "7200" are all valid values for the custom min interval, and they all have the same result.
4) The config file template is changed to account …

[NUTCH-3103] Fixed custom max intervals for AdaptiveFetchSchedule

---

conf/nutch-default.xml

Modify the default value of the configuration property `fetcher.max.exceptions.per.queue` from `-1` ("unlimited") to `5`, so that blocked queues are purged earlier.

NUTCH-3114 Avoid stale fetching when only URLs from queues blocked by the exponential backoff remain

---

conf/log4j2.xml

- remove "package" attribute in log4j2.xml

NUTCH-3119 Log4j package scanning is deprecated

---

.github/workflows/master-build.yml

Upgrade "paths-changes-filter" action to version 3.0.2 but pin the version using the Git commit hash.

NUTCH-3124 Github workflow not run because of uncertified action "paths-changes-filter"

---

ivy/ivy.xml
src/plugin/parse-js/src/test/org/apache/nutch/parse/js/TestJSParseFilter.java
src/test/org/apache/nutch/protocol/AbstractHttpProtocolPluginTest.java

This PR removes all dependencies on JUnit 4:
- migrate unit tests of plugin parse-js
- finish migration of AbstractHttpProtocolPluginTest
- exclude transitive dependencies from MRUnit on
- JUnit 4
- further outdated but unused test libraries

NUTCH-2887 Remove all dependencies on JUnit 4
